GPM: GPM::Tools::Utils Class Reference
GPM::Tools::Utils Class Reference final
#include <Utils.h>
Public Member Functions
Utils ()=delete
Utils ()=delete
Static Public Member Functions
template<typename T >
static T ToRadians (const T p_angle)
Convert the given angle to radians.
template<typename T >
static T ToDegrees (const T p_angle)
Convert the given angle to degrees in float precision.
template<typename T >
static T Lerp (const T p_a, const T p_b, const T p_alpha)
Linearly interpolates between two values.
template<typename T >
static T Pow (const T p_value, const int p_exp)
Return the pow of a numeric value with an integer exponent.
template<typename T >
static T Pow (const T p_value, const float p_exp)
Return the pow of a numeric value with a float exponent.
template<typename T >
static T SquareRoot (const T p_value)
Return the square root of a numeric value.
template<typename T >
static T SquareRootF (const T p_value)
Return the square root of a numeric value with float precision.
template<typename T >
static T Root (const T p_value, const float p_nRoot)
Return the root of a numeric value.
static int GreatestCommonDivider (const int p_a, const int p_b)
Return the greatest common divider of the two given integers.
static int LeastCommonMultiple (const int p_a, const int p_b)
Return the smallest common divider of the two given integers.
template<typename T >
static T GetDecimalPart (const T p_value)
Return the decimal part of a float as an integer.
template<typename T >
static T Abs (const T p_value)
Return the absolute value of a numeric value.
static double Sin (const double p_value)
Mathematics sinus implementation.
static float SinF (const float p_value)
Mathematics sinus implementation with float precision.
static double Cos (const double p_value)
Mathematics co-sinus implementation.
static float CosF (const float p_value)
Mathematics co-sinus implementation with float precision.
static double Tan (const double p_value)
Mathematics tangent implementation.
static float TanF (const float p_value)
Mathematics tangent implementation with float precision.
static double Arccos (const double p_value)
static float ArccosF (const float p_value)
Mathematics arc co-sinus implementation with float precision.
static double Arcsin (const double p_value)
Mathematics arc sinus implementation.
static float ArcsinF (const float p_value)
static double Arctan (const double p_value)
Mathematics arc tangent implementation.
static float ArctanF (const float p_value)
Mathematics arc tangent implementation with float precision.
static double Arctan2 (const double p_valueYx, const double p_valueXx)
Mathematics arc tangent implementation.
static float Arctan2F (const float p_valueYx, const float p_valueXx)
Mathematics arc tangent implementation with float precision.
template<typename T >
static T Sign (const T p_value)
Return the sign of the parameter.
template<typename T >
static T ToRadians (const T p_angle)
Convert the given angle to radians.
template<typename T >
static T ToDegrees (const T p_angle)
Convert the given angle to degrees in float precision.
template<typename T >
static T Lerp (const T p_a, const T p_b, const T p_alpha)
Linearly interpolates between two values.
template<typename T >
static T Pow (const T p_value, const int p_exp)
Return the pow of a numeric value with an integer exponent.
template<typename T >
static T Pow (const T p_value, const float p_exp)
Return the pow of a numeric value with a float exponent.
template<typename T >
static T SquareRoot (const T p_value)
Return the square root of a numeric value.
template<typename T >
static T SquareRootF (const T p_value)
Return the square root of a numeric value with float precision.
template<typename T >
static T Root (const T p_value, const float p_nRoot)
Return the root of a numeric value.
static int GreatestCommonDivider (const int p_a, const int p_b)
Return the greatest common divider of the two given integers.
static int LeastCommonMultiple (const int p_a, const int p_b)
Return the smallest common divider of the two given integers.
template<typename T >
static T GetDecimalPart (const T p_value)
Return the decimal part of a float as an integer.
template<typename T >
static T Abs (const T p_value)
Return the absolute value of a numeric value.
static double Sin (const double p_value)
Mathematics sinus implementation.
static float SinF (const float p_value)
Mathematics sinus implementation with float precision.
static double Cos (const double p_value)
Mathematics co-sinus implementation.
static float CosF (const float p_value)
Mathematics co-sinus implementation with float precision.
static double Tan (const double p_value)
Mathematics tangent implementation.
static float TanF (const float p_value)
Mathematics tangent implementation with float precision.
static double Arccos (const double p_value)
static float ArccosF (const float p_value)
Mathematics arc co-sinus implementation with float precision.
static double Arcsin (const double p_value)
Mathematics arc sinus implementation.
static float ArcsinF (const float p_value)
static double Arctan (const double p_value)
Mathematics arc tangent implementation.
static float ArctanF (const float p_value)
Mathematics arc tangent implementation with float precision.
static double Arctan2 (const double p_valueYx, const double p_valueXx)
Mathematics arc tangent implementation.
static float Arctan2F (const float p_valueYx, const float p_valueXx)
Mathematics arc tangent implementation with float precision.
template<typename T >
static T Sign (const T p_value)
Return the sign of the parameter.
Detailed Description
Return the square root of a numeric value
Parameters
nUtils class provides some simple mathematics tools, such as operations, pow, root, trigonometry stuffs...
Definition at line 24 of file Utils.h.
Constructor & Destructor Documentation
Utils() [1/2]
GPM::Tools::Utils::Utils () delete
Utils() [2/2]
GPM::Tools::Utils::Utils () delete
Member Function Documentation
Abs() [1/2]
template<typename T > T GPM::Tools::Utils::Abs (const T p_value) inline static
Return the absolute value of a numeric value.
Parameters
p_value The value to make absolute
Returns
The absolute value
Definition at line 175 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "The value to Abs must be arithmetic");
         return static_cast<T>(std::abs(p_value));
     }
Referenced by GPM::Quaternion::ToEuler().
Abs() [2/2]
template<typename T > static T GPM::Tools::Utils::Abs (const T p_value) static
Return the absolute value of a numeric value.
Parameters
p_value The value to make absolute
Returns
The absolute value
Arccos() [1/2]
double GPM::Tools::Utils::Arccos (const double p_value) inline static
@biref Mathematics arc co-sinus implementation
Parameters
p_value Value
Returns
The result in radians
Definition at line 92 of file Utils.inl.
     {
         return std::acos(p_value);
     }
Referenced by GPM::Vector2< T >::Angle(), GPM::Vector4< T >::Angle(), GPM::Quaternion::LookRotation(), and GPM::Quaternion::Slerp().
Arccos() [2/2]
static double GPM::Tools::Utils::Arccos (const double p_value) static
@biref Mathematics arc co-sinus implementation
Parameters
p_value Value
Returns
The result in radians
ArccosF() [1/2]
float GPM::Tools::Utils::ArccosF (const float p_value) inline static
Mathematics arc co-sinus implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
Definition at line 97 of file Utils.inl.
     {
         return std::acosf(p_value);
     }
ArccosF() [2/2]
static float GPM::Tools::Utils::ArccosF (const float p_value) static
Mathematics arc co-sinus implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
Arcsin() [1/2]
double GPM::Tools::Utils::Arcsin (const double p_value) inline static
Mathematics arc sinus implementation.
Parameters
p_value Value
Returns
The result in radians
Definition at line 102 of file Utils.inl.
     {
         return std::asin(p_value);
     }
Referenced by GPM::Quaternion::ToEuler().
Arcsin() [2/2]
static double GPM::Tools::Utils::Arcsin (const double p_value) static
Mathematics arc sinus implementation.
Parameters
p_value Value
Returns
The result in radians
ArcsinF() [1/2]
float GPM::Tools::Utils::ArcsinF (const float p_value) inline static
Mathematics arc sinus implementation with float precision
Parameters
p_value Value
Returns
The result in radians
Definition at line 107 of file Utils.inl.
     {
         return std::asinf(p_value);
     }
ArcsinF() [2/2]
static float GPM::Tools::Utils::ArcsinF (const float p_value) static
Mathematics arc sinus implementation with float precision
Parameters
p_value Value
Returns
The result in radians
Arctan() [1/2]
double GPM::Tools::Utils::Arctan (const double p_value) inline static
Mathematics arc tangent implementation.
Parameters
p_value Value
Returns
The result in radians
Definition at line 112 of file Utils.inl.
     {
         return std::atan(p_value);
     }
Arctan() [2/2]
static double GPM::Tools::Utils::Arctan (const double p_value) static
Mathematics arc tangent implementation.
Parameters
p_value Value
Returns
The result in radians
Arctan2() [1/2]
double GPM::Tools::Utils::Arctan2 (const double p_valueYx, const double p_valueXx) inline static
Mathematics arc tangent implementation.
Parameters
p_valueYx Left value
p_valueXx Right value
Returns
The result in radians
Definition at line 122 of file Utils.inl.
     {
         return std::atan2(p_valueYx, p_valueXx);
     }
Referenced by GPM::Quaternion::ToEuler().
Arctan2() [2/2]
static double GPM::Tools::Utils::Arctan2 (const double p_valueYx, const double p_valueXx) static
Mathematics arc tangent implementation.
Parameters
p_valueYx Left value
p_valueXx Right value
Returns
The result in radians
Arctan2F() [1/2]
float GPM::Tools::Utils::Arctan2F (const float p_valueYx, const float p_valueXx) inline static
Mathematics arc tangent implementation with float precision.
Parameters
p_valueYx
p_valueXx
Returns
The result in radians
Definition at line 127 of file Utils.inl.
     {
         return std::atan2f(p_valueYx, p_valueXx);
     }
Arctan2F() [2/2]
static float GPM::Tools::Utils::Arctan2F (const float p_valueYx, const float p_valueXx) static
Mathematics arc tangent implementation with float precision.
Parameters
p_valueYx
p_valueXx
Returns
The result in radians
ArctanF() [1/2]
static float GPM::Tools::Utils::ArctanF (const float p_value) static
Mathematics arc tangent implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
ArctanF() [2/2]
float GPM::Tools::Utils::ArctanF (const float p_value) inline static
Mathematics arc tangent implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
Definition at line 117 of file Utils.inl.
     {
         return std::atanf(p_value);
     }
Cos() [1/2]
static double GPM::Tools::Utils::Cos (const double p_value) static
Mathematics co-sinus implementation.
Parameters
p_value Value
Returns
The result in radians
Cos() [2/2]
double GPM::Tools::Utils::Cos (const double p_value) inline static
Mathematics co-sinus implementation.
Parameters
p_value Value
Returns
The result in radians
Definition at line 72 of file Utils.inl.
     {
         return std::cos(p_value);
     }
Referenced by GPM::Quaternion::ConvertToUnitNormQuaternion(), GPM::Quaternion::CreateFromAxisAngle(), GPM::Matrix3< T >::CreateRotation(), GPM::Vector4< T >::Slerp(), GPM::Quaternion::ToQuaternion(), and GPM::Quaternion::ToUnitNormQuaternion().
CosF() [1/2]
float GPM::Tools::Utils::CosF (const float p_value) inline static
Mathematics co-sinus implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
Definition at line 77 of file Utils.inl.
     {
         return std::cosf(p_value);
     }
Referenced by GPM::Matrix3< T >::Rotate().
CosF() [2/2]
static float GPM::Tools::Utils::CosF (const float p_value) static
Mathematics co-sinus implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
GetDecimalPart() [1/2]
template<typename T > static T GPM::Tools::Utils::GetDecimalPart (const T p_value) static
Return the decimal part of a float as an integer.
Parameters
p_value The value from which we take the decimal part
Returns
The decimal part
GetDecimalPart() [2/2]
template<typename T > T GPM::Tools::Utils::GetDecimalPart (const T p_value) inline static
Return the decimal part of a float as an integer.
Parameters
p_value The value from which we take the decimal part
Returns
The decimal part
Definition at line 56 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "Sign function should only be used with arithmetic types");
         return mod(p_value, T(1.0));
     }
GreatestCommonDivider() [1/2]
static int GPM::Tools::Utils::GreatestCommonDivider (const int p_a, const int p_b) static
Return the greatest common divider of the two given integers.
Parameters
p_a Left value
p_b Right value
Returns
The greatest common divider
GreatestCommonDivider() [2/2]
int GPM::Tools::Utils::GreatestCommonDivider (const int p_a, const int p_b) inline static
Return the greatest common divider of the two given integers.
Parameters
p_a Left value
p_b Right value
Returns
The greatest common divider
Definition at line 39 of file Utils.inl.
     {
         for (int divisor = std::min(p_a, p_b); divisor > 0; divisor--) {
             if (0 == p_a % divisor && 0 == p_b % divisor) {
                 return divisor;
             }
         }
         return p_b;
     }
Referenced by LeastCommonMultiple().
LeastCommonMultiple() [1/2]
static int GPM::Tools::Utils::LeastCommonMultiple (const int p_a, const int p_b) static
Return the smallest common divider of the two given integers.
Parameters
p_a Left value
p_b Right value
Returns
The least common multiple
LeastCommonMultiple() [2/2]
int GPM::Tools::Utils::LeastCommonMultiple (const int p_a, const int p_b) inline static
Return the smallest common divider of the two given integers.
Parameters
p_a Left value
p_b Right value
Returns
The least common multiple
Definition at line 50 of file Utils.inl.
     {
         return p_a * p_b / GreatestCommonDivider(p_a, p_b);
     }
References GreatestCommonDivider().
Lerp() [1/2]
template<typename T > T GPM::Tools::Utils::Lerp (const T p_a, const T p_b, const T p_alpha) inline static
Linearly interpolates between two values.
Parameters
p_a Start value
p_b End value
p_alpha Coefficient
Returns
The interpolated value
Definition at line 26 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "Lerp function should only be used with arithmetic types");
         if (p_alpha >= T(0.0) && p_alpha <= T(1.0))
             return p_a + (p_b - p_a) * p_alpha;
         if (p_alpha < T(0.0))
             return p_a;
         return p_b;
     }
Lerp() [2/2]
template<typename T > static T GPM::Tools::Utils::Lerp (const T p_a, const T p_b, const T p_alpha) static
Linearly interpolates between two values.
Parameters
p_a Start value
p_b End value
p_alpha Coefficient
Returns
The interpolated value
Pow() [1/4]
template<typename T > T GPM::Tools::Utils::Pow (const T p_value, const int p_exp) inline static
Return the pow of a numeric value with an integer exponent.
Parameters
p_value The value
p_exp The power
Returns
The result of power
Definition at line 140 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "The value to pow must be arithmetic");
         return static_cast<T>(std::pow(p_value, p_exp));
     }
Referenced by GPM::Vector2< T >::Distance(), and GPM::Vector2< T >::Magnitude().
Pow() [2/4]
template<typename T > static T GPM::Tools::Utils::Pow (const T p_value, const int p_exp) static
Return the pow of a numeric value with an integer exponent.
Parameters
p_value The value
p_exp The power
Returns
The result of power
Pow() [3/4]
template<typename T > static T GPM::Tools::Utils::Pow (const T p_value, const float p_exp) static
Return the pow of a numeric value with a float exponent.
Parameters
p_value The value
p_exp The power
Returns
The result of power
Pow() [4/4]
template<typename T > T GPM::Tools::Utils::Pow (const T p_value, const float p_exp) inline static
Return the pow of a numeric value with a float exponent.
Parameters
p_value The value
p_exp The power
Returns
The result of power
Definition at line 147 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "The value to pow must be arithmetic");
         return static_cast<T>(std::pow(p_value, p_exp));
     }
Root() [1/2]
template<typename T > static T GPM::Tools::Utils::Root (const T p_value, const float p_nRoot) static
Return the root of a numeric value.
Parameters
p_value Value
p_nRoot Root
Returns
The root
Root() [2/2]
template<typename T > T GPM::Tools::Utils::Root (const T p_value, const float p_nRoot) inline static
Return the root of a numeric value.
Parameters
p_value Value
p_nRoot Root
Returns
The root
Definition at line 168 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "The value to root must be arithmetic");
         return static_cast<T>(std::pow(p_value, 1 / p_nRoot));
     }
Sign() [1/2]
template<typename T > static T GPM::Tools::Utils::Sign (const T p_value) static
Return the sign of the parameter.
Parameters
p_value The value to check
Returns
The sign of p_value of type T
Sign() [2/2]
template<typename T > T GPM::Tools::Utils::Sign (const T p_value) inline static
Return the sign of the parameter.
Parameters
p_value The value to check
Returns
The sign of p_value of type T
Definition at line 133 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "Sign function should only be used with arithmetic types");
         return (p_value > static_cast<T>(0)) ? static_cast<T>(1) : ((p_value < static_cast<T>(0)) ? static_cast<T>(-1) : static_cast<T>(0));
     }
Sin() [1/2]
static double GPM::Tools::Utils::Sin (const double p_value) static
Mathematics sinus implementation.
Parameters
p_value Value
Returns
The result in radians
Sin() [2/2]
double GPM::Tools::Utils::Sin (const double p_value) inline static
Mathematics sinus implementation.
Parameters
p_value Value
Returns
The result in radians
Definition at line 62 of file Utils.inl.
     {
         return std::sin(p_value);
     }
Referenced by GPM::Quaternion::ConvertToUnitNormQuaternion(), GPM::Quaternion::CreateFromAxisAngle(), GPM::Matrix3< T >::CreateRotation(), GPM::Quaternion::Slerp(), GPM::Vector4< T >::Slerp(), GPM::Quaternion::ToQuaternion(), and GPM::Quaternion::ToUnitNormQuaternion().
SinF() [1/2]
float GPM::Tools::Utils::SinF (const float p_value) inline static
Mathematics sinus implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
Definition at line 67 of file Utils.inl.
     {
         return std::sinf(p_value);
     }
Referenced by GPM::Matrix3< T >::Rotate().
SinF() [2/2]
static float GPM::Tools::Utils::SinF (const float p_value) static
Mathematics sinus implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
SquareRoot() [1/2]
template<typename T > static T GPM::Tools::Utils::SquareRoot (const T p_value) static
Return the square root of a numeric value.
Parameters
p_value Value
Returns
The square root
SquareRoot() [2/2]
template<typename T > T GPM::Tools::Utils::SquareRoot (const T p_value) inline static
Return the square root of a numeric value.
Parameters
p_value Value
Returns
The square root
Definition at line 154 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "The value to root must be arithmetic");
         return static_cast<T>(std::sqrt(p_value));
     }
Referenced by GPM::Vector2< T >::Distance(), and GPM::Quaternion::Norm().
SquareRootF() [1/2]
template<typename T > static T GPM::Tools::Utils::SquareRootF (const T p_value) static
Return the square root of a numeric value with float precision.
Parameters
p_value The
Returns
The result square root
SquareRootF() [2/2]
template<typename T > T GPM::Tools::Utils::SquareRootF (const T p_value) inline static
Return the square root of a numeric value with float precision.
Parameters
p_value The
Returns
The result square root
Definition at line 161 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "The value to root must be arithmetic");
         return static_cast<T>(std::sqrtf(p_value));
     }
Referenced by GPM::Vector4< T >::Distance(), and GPM::Vector4< T >::Magnitude().
Tan() [1/2]
double GPM::Tools::Utils::Tan (const double p_value) inline static
Mathematics tangent implementation.
Parameters
p_value Value
Returns
The result in radians
Definition at line 82 of file Utils.inl.
     {
         return std::tan(p_value);
     }
Tan() [2/2]
static double GPM::Tools::Utils::Tan (const double p_value) static
Mathematics tangent implementation.
Parameters
p_value Value
Returns
The result in radians
TanF() [1/2]
static float GPM::Tools::Utils::TanF (const float p_value) static
Mathematics tangent implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
TanF() [2/2]
float GPM::Tools::Utils::TanF (const float p_value) inline static
Mathematics tangent implementation with float precision.
Parameters
p_value Value
Returns
The result in radians
Definition at line 87 of file Utils.inl.
     {
         return std::tanf(p_value);
     }
ToDegrees() [1/2]
template<typename T > static T GPM::Tools::Utils::ToDegrees (const T p_angle) static
Convert the given angle to degrees in float precision.
Parameters
p_angle (In radians)
Returns
The result in degrees
ToDegrees() [2/2]
template<typename T > T GPM::Tools::Utils::ToDegrees (const T p_angle) inline static
Convert the given angle to degrees in float precision.
Parameters
p_angle (In radians)
Returns
The result in degrees
Definition at line 18 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "ToDegrees function should only be used with arithmetic types");
         return p_angle * (T(180.0) / static_cast<T>(M_PI));
     }
References GPM::Tools::M_PI.
Referenced by GPM::Quaternion::ToEuler().
ToRadians() [1/2]
template<typename T > T GPM::Tools::Utils::ToRadians (const T p_angle) inline static
Convert the given angle to radians.
Parameters
p_angle (In degrees)
Returns
The angle in radians
Definition at line 10 of file Utils.inl.
     {
         static_assert(std::is_arithmetic<T>::value, "ToRadians function should only be used with arithmetic types");
         return p_angle * (static_cast<T>(M_PI) / T(180.0));
     }
References GPM::Tools::M_PI.
Referenced by GPM::Quaternion::ConvertToUnitNormQuaternion(), GPM::Quaternion::MakeFromEuler(), GPM::Vector4< T >::Slerp(), and GPM::Quaternion::ToUnitNormQuaternion().
ToRadians() [2/2]
template<typename T > static T GPM::Tools::Utils::ToRadians (const T p_angle) static
Convert the given angle to radians.
Parameters
p_angle (In degrees)
Returns
The angle in radians
The documentation for this class was generated from the following files:
GPM/include/GPM/Tools/Utils.h
GPM/include/GPM/Tools/Utils.inl