GPM: GPM::Matrix4< T > Struct Template Reference
GPM::Matrix4< T > Struct Template Reference
#include <Matrix4.h>
Public Member Functions
constexpr Matrix4 ()
~Matrix4 ()=default
constexpr Matrix4 (const Matrix4< T > &p_matrix)
constexpr Matrix4 (Matrix4< T > &&p_matrix) noexcept
constexpr Matrix4 (const Vector3< T > &p_vector)
constexpr Matrix4 (const T p_data[16])
constexpr Matrix4 (const T p_00, const T p_01, const T p_02, const T p_03, const T p_10, const T p_11, const T p_12, const T p_13, const T p_20, const T p_21, const T p_22, const T p_23, const T p_30, const T p_31, const T p_32, const T p_33)
constexpr bool isIdentity ()
constexpr T Determinant ()
constexpr Matrix4< T > & Transpose ()
constexpr Matrix4< T > & Normalize ()
template<typename U >
constexpr Matrix4< T > & Scale (const Vector3< U > &p_scale)
constexpr Matrix4< T > & Rotate (const Quaternion &p_rotation)
template<typename U >
constexpr Matrix4< T > & Translate (const Vector3< U > &p_translate)
template<typename U >
constexpr Matrix4< T > & Transform (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
constexpr Matrix4< T > Adjugate ()
constexpr void SetColumn (int p_column, const Vector4< T > &p_vector)
constexpr void SetRow (int p_row, const Vector4< T > &p_vector)
constexpr std::string ToString () noexcept
template<typename U >
Matrix4< T > & Add (const Matrix4< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
constexpr Matrix4< T > operator+ (const Matrix4< U > &p_other) const
Return the summation of other matrix and current matrix.
template<typename U >
Matrix4< T > operator+= (const Matrix4< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
Matrix4< T > Subtract (const Matrix4< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
constexpr Matrix4< T > operator- (const Matrix4< U > &p_other) const
Return the subtraction of other matrix and current matrix.
template<typename U >
Matrix4< T > & operator-= (const Matrix4< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
Matrix4< T > & Multiply (U p_scalar)
Multiply scalar to elements.
template<typename U >
Matrix4< T > & Multiply (const Matrix4< U > &p_other)
Multiply matrix with another matrix.
template<typename U >
Vector4< U > & Multiply (const Vector4< U > &p_other)
template<typename U >
constexpr Matrix4< T > operator * (const Matrix4< U > &p_other) const
Multiply matrix to the current matrix.
template<typename U >
Matrix4< T > & operator *= (const Matrix4< U > &p_other)
Multiply matrix to the current matrix.
bool Equals (const Matrix4< T > &p_other)
Vector4< T > operator * (const Vector4< T > &p_vector)
bool operator== (const Matrix4< T > &p_matrix)
bool operator!= (const Matrix4< T > &p_matrix)
template<typename U >
void operator= (const Matrix4< U > &p_matrix)
T operator[] (int p_position)
constexpr Matrix4 ()
~Matrix4 ()=default
constexpr Matrix4 (const Matrix4< T > &p_matrix)
constexpr Matrix4 (Matrix4< T > &&p_matrix) noexcept
constexpr Matrix4 (const Vector3< T > &p_vector)
constexpr Matrix4 (const T p_data[16])
constexpr Matrix4 (const T p_00, const T p_01, const T p_02, const T p_03, const T p_10, const T p_11, const T p_12, const T p_13, const T p_20, const T p_21, const T p_22, const T p_23, const T p_30, const T p_31, const T p_32, const T p_33)
constexpr bool isIdentity ()
constexpr T Determinant ()
constexpr Matrix4< T > & Transpose ()
constexpr Matrix4< T > & Normalize ()
template<typename U >
constexpr Matrix4< T > & Scale (const Vector3< U > &p_scale)
constexpr Matrix4< T > & Rotate (const Quaternion &p_rotation)
template<typename U >
constexpr Matrix4< T > & Translate (const Vector3< U > &p_translate)
template<typename U >
constexpr Matrix4< T > & Transform (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
constexpr Matrix4< T > Adjugate ()
constexpr void SetColumn (int p_column, const Vector4< T > &p_vector)
constexpr void SetRow (int p_row, const Vector4< T > &p_vector)
constexpr std::string ToString () noexcept
template<typename U >
Matrix4< T > & Add (const Matrix4< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
constexpr Matrix4< T > operator+ (const Matrix4< U > &p_other) const
Return the summation of other matrix and current matrix.
template<typename U >
Matrix4< T > operator+= (const Matrix4< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
Matrix4< T > Subtract (const Matrix4< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
constexpr Matrix4< T > operator- (const Matrix4< U > &p_other) const
Return the subtraction of other matrix and current matrix.
template<typename U >
Matrix4< T > & operator-= (const Matrix4< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
Matrix4< T > & Multiply (U p_scalar)
Multiply scalar to elements.
template<typename U >
Matrix4< T > & Multiply (const Matrix4< U > &p_other)
Multiply matrix with another matrix.
template<typename U >
Vector4< U > & Multiply (const Vector4< U > &p_other)
template<typename U >
constexpr Matrix4< T > operator * (const Matrix4< U > &p_other) const
Multiply matrix to the current matrix.
template<typename U >
Matrix4< T > & operator *= (const Matrix4< U > &p_other)
Multiply matrix to the current matrix.
bool Equals (const Matrix4< T > &p_other)
Vector4< T > operator * (const Vector4< T > &p_vector)
bool operator== (const Matrix4< T > &p_matrix)
bool operator!= (const Matrix4< T > &p_matrix)
template<typename U >
void operator= (const Matrix4< U > &p_matrix)
T operator[] (int p_position)
template<typename U >
constexpr Matrix4< T > & Scale (const Vector3< U > &p_scale)
template<typename U >
constexpr Matrix4< T > CreateScale (const Vector3< U > &p_scale)
template<typename U >
constexpr Matrix4< T > & Translate (const Vector3< U > &p_translate)
template<typename U >
constexpr Matrix4< T > CreateTranslation (const Vector3< U > &p_translate)
template<typename U >
constexpr Matrix4< T > & Transform (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
template<typename U >
constexpr Matrix4< T > CreateTransformation (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
template<typename U >
Matrix4< T > & Add (const Matrix4< U > &p_other)
template<typename U >
constexpr Matrix4< T > Add (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
template<typename U >
constexpr Matrix4< T > operator+ (const Matrix4< U > &p_other) const
template<typename U >
Matrix4< T > operator+= (const Matrix4< U > &p_other)
template<typename U >
Matrix4< T > Subtract (const Matrix4< U > &p_other)
template<typename U >
constexpr Matrix4< T > Subtract (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
template<typename U >
constexpr Matrix4< T > operator- (const Matrix4< U > &p_other) const
template<typename U >
Matrix4< T > & operator-= (const Matrix4< U > &p_other)
template<typename U >
Matrix4< T > & Multiply (U p_scalar)
template<typename U >
constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, U p_right)
template<typename U >
Matrix4< T > & Multiply (const Matrix4< U > &p_other)
template<typename U >
constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
template<typename U >
Vector4< U > & Multiply (const Vector4< U > &p_other)
template<typename U >
constexpr Matrix4< T > operator * (const Matrix4< U > &p_other) const
template<typename U >
Matrix4< T > & operator *= (const Matrix4< U > &p_other)
template<typename U >
Vector4< T > Multiply (const Matrix4< U > &p_matrix, const Vector4< T > &p_vector)
template<typename U >
void Set (Matrix4< T > &p_matrix, const Matrix4< U > &p_other)
template<typename T >
Vector4< T > operator * (const Vector4< T > &p_vector)
template<typename U >
void operator= (const Matrix4< U > &p_matrix)
template<typename U >
constexpr Matrix4< T > & Scale (const Vector3< U > &p_scale)
template<typename U >
constexpr Matrix4< T > CreateScale (const Vector3< U > &p_scale)
template<typename U >
constexpr Matrix4< T > & Translate (const Vector3< U > &p_translate)
template<typename U >
constexpr Matrix4< T > CreateTranslation (const Vector3< U > &p_translate)
template<typename U >
constexpr Matrix4< T > & Transform (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
template<typename U >
constexpr Matrix4< T > CreateTransformation (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
template<typename U >
Matrix4< T > & Add (const Matrix4< U > &p_other)
template<typename U >
constexpr Matrix4< T > Add (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
template<typename U >
constexpr Matrix4< T > operator+ (const Matrix4< U > &p_other) const
template<typename U >
Matrix4< T > operator+= (const Matrix4< U > &p_other)
template<typename U >
Matrix4< T > Subtract (const Matrix4< U > &p_other)
template<typename U >
constexpr Matrix4< T > Subtract (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
template<typename U >
constexpr Matrix4< T > operator- (const Matrix4< U > &p_other) const
template<typename U >
Matrix4< T > & operator-= (const Matrix4< U > &p_other)
template<typename U >
Matrix4< T > & Multiply (U p_scalar)
template<typename U >
constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, U p_right)
template<typename U >
Matrix4< T > & Multiply (const Matrix4< U > &p_other)
template<typename U >
constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
template<typename U >
Vector4< U > & Multiply (const Vector4< U > &p_other)
template<typename U >
constexpr Matrix4< T > operator * (const Matrix4< U > &p_other) const
template<typename U >
Matrix4< T > & operator *= (const Matrix4< U > &p_other)
template<typename U >
Vector4< T > Multiply (const Matrix4< U > &p_matrix, const Vector4< T > &p_vector)
template<typename U >
void Set (Matrix4< T > &p_matrix, const Matrix4< U > &p_other)
template<typename T >
Vector4< T > operator * (const Vector4< T > &p_vector)
template<typename U >
void operator= (const Matrix4< U > &p_matrix)
Static Public Member Functions
static constexpr T Determinant (const Matrix4< T > &p_matrix)
static constexpr Matrix4< T > Transpose (const Matrix4< T > &p_matrix)
static constexpr Matrix4< T > Normalize (const Matrix4< T > &p_matrix)
template<typename U >
static constexpr Matrix4< T > CreateScale (const Vector3< U > &p_scale)
static constexpr Matrix4< T > CreateRotation (const Quaternion &p_rotation)
template<typename U >
static constexpr Matrix4< T > CreateTranslation (const Vector3< U > &p_translate)
template<typename U >
static constexpr Matrix4< T > CreateTransformation (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
static constexpr Matrix4< T > CreateAdjugate (const Matrix4< T > &p_matrix)
static constexpr Matrix4< T > Inverse (const Matrix4< T > &p_matrix)
static Matrix4< T > LookAt (const Vector3< T > &p_from, const Vector3< T > &p_to, const Vector3< T > &p_up={ 0, 1, 0 })
static T GetMinor (Matrix3< T > p_minor)
static constexpr std::string ToString (const Matrix4< T > &p_matrix)
template<typename U >
static constexpr Matrix4< T > Add (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
Add left matrix to the right matrix.
template<typename U >
static constexpr Matrix4< T > Subtract (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
Subtract left matrix to the right matrix.
template<typename U >
static constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, U p_right)
Multiply scalar to matrix left.
template<typename U >
static constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
Multiply matrix to matrix left.
template<typename U >
static Vector4< T > Multiply (const Matrix4< U > &p_matrix, const Vector4< T > &p_vector)
template<typename U >
static void Set (Matrix4< T > &p_matrix, const Matrix4< U > &p_other)
static constexpr T Determinant (const Matrix4< T > &p_matrix)
static constexpr Matrix4< T > Transpose (const Matrix4< T > &p_matrix)
static constexpr Matrix4< T > Normalize (const Matrix4< T > &p_matrix)
template<typename U >
static constexpr Matrix4< T > CreateScale (const Vector3< U > &p_scale)
static constexpr Matrix4< T > CreateRotation (const Quaternion &p_rotation)
template<typename U >
static constexpr Matrix4< T > CreateTranslation (const Vector3< U > &p_translate)
template<typename U >
static constexpr Matrix4< T > CreateTransformation (const Vector3< U > &p_translate, const Quaternion &p_rotation, const Vector3< U > &p_scale)
static constexpr Matrix4< T > CreateAdjugate (const Matrix4< T > &p_matrix)
static constexpr Matrix4< T > Inverse (const Matrix4< T > &p_matrix)
static Matrix4< T > LookAt (const Vector3< T > &p_from, const Vector3< T > &p_to, const Vector3< T > &p_up={ 0, 1, 0 })
static T GetMinor (Matrix3< T > p_minor)
static constexpr std::string ToString (const Matrix4< T > &p_matrix)
template<typename U >
static constexpr Matrix4< T > Add (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
Add left matrix to the right matrix.
template<typename U >
static constexpr Matrix4< T > Subtract (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
Subtract left matrix to the right matrix.
template<typename U >
static constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, U p_right)
Multiply scalar to matrix left.
template<typename U >
static constexpr Matrix4< T > Multiply (const Matrix4< T > &p_left, const Matrix4< U > &p_right)
Multiply matrix to matrix left.
template<typename U >
static Vector4< T > Multiply (const Matrix4< U > &p_matrix, const Vector4< T > &p_vector)
template<typename U >
static void Set (Matrix4< T > &p_matrix, const Matrix4< U > &p_other)
Data Fields
T m_data [16]
Static Public Attributes
static Matrix4< T > identity
This is a const matrix that has 1 in the diagonal and 0 elsewhere.
static Matrix4< T > zero
This is a const matrix that has 0 everywhere.
Detailed Description
template<typename T>
struct GPM::Matrix4< T >
A standard 4 by 4 Matrix. Default value is an identity matrix
Definition at line 14 of file Matrix4.h.
Constructor & Destructor Documentation
Matrix4() [1/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 ()
~Matrix4() [1/2]
template<typename T> GPM::Matrix4< T >::~Matrix4 () default
Matrix4() [2/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 (const Matrix4< T > & p_matrix)
Matrix4() [3/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 (Matrix4< T > && p_matrix) noexcept
Matrix4() [4/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 (const Vector3< T > & p_vector)
Matrix4() [5/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 (const T p_data[16])
Matrix4() [6/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 (const T p_00, const T p_01, const T p_02, const T p_03, const T p_10, const T p_11, const T p_12, const T p_13, const T p_20, const T p_21, const T p_22, const T p_23, const T p_30, const T p_31, const T p_32, const T p_33)
Matrix4() [7/12]
template<typename T> constexpr Matrix4::Matrix4 ()
Definition at line 23 of file Matrix4.inl.
 {
     memcpy(m_data, identity.m_data, 16 * sizeof(T));
 }
~Matrix4() [2/2]
template<typename T> GPM::Matrix4< T >::~Matrix4 () default
Matrix4() [8/12]
template<typename T> constexpr Matrix4::Matrix4 (const Matrix4< T > & p_matrix)
Definition at line 29 of file Matrix4.inl.
 {
     memcpy(m_data, p_matrix.m_data, 16 * sizeof(T));
 }
References GPM::Matrix4< T >::m_data.
Matrix4() [9/12]
template<typename T> constexpr GPM::Matrix4< T >::Matrix4 (Matrix4< T > && p_matrix) noexcept
Matrix4() [10/12]
template<typename T> constexpr Matrix4::Matrix4 (const Vector3< T > & p_vector)
Definition at line 42 of file Matrix4.inl.
 {
     m_data[0] = p_vector.x;
     m_data[5] = p_vector.y;
     m_data[10] = p_vector.z;
 }
References GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
Matrix4() [11/12]
template<typename T> constexpr Matrix4::Matrix4 (const T p_data[16])
Definition at line 50 of file Matrix4.inl.
 {
     if (p_data == nullptr)
         return;
     memcpy(m_data, p_data, 16 * sizeof(T));
 }
Matrix4() [12/12]
template<typename T> constexpr Matrix4::Matrix4 (const T p_00, const T p_01, const T p_02, const T p_03, const T p_10, const T p_11, const T p_12, const T p_13, const T p_20, const T p_21, const T p_22, const T p_23, const T p_30, const T p_31, const T p_32, const T p_33)
Definition at line 59 of file Matrix4.inl.
     : m_data{p_00, p_01, p_02, p_03, p_10, p_11, p_12, p_13, p_20, p_21, p_22, p_23, p_30, p_31, p_32, p_33}
 {
 }
Member Function Documentation
Add() [1/8]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Add (const Matrix4< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
Referenced by GPM::Matrix4< T >::Add().
Add() [2/8]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Add (const Matrix4< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
Add() [3/8]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Add (const Matrix4< T > & p_left, const Matrix4< U > & p_right) static
Add left matrix to the right matrix.
Parameters
p_left : The first matrix you want to add
p_right : The second matrix to be added to the first one
Returns
The copy of the Matrix operation result
Add() [4/8]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Add (const Matrix4< T > & p_left, const Matrix4< U > & p_right) static
Add left matrix to the right matrix.
Parameters
p_left : The first matrix you want to add
p_right : The second matrix to be added to the first one
Returns
The copy of the Matrix operation result
Add() [5/8]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Add (const Matrix4< U > & p_other)
Definition at line 345 of file Matrix4.inl.
 {
     for (int i = 0; i < 16; i++)
     {
         m_data[i] += p_other.m_data[i];
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Add() [6/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Add (const Matrix4< T > & p_left, const Matrix4< U > & p_right)
Definition at line 357 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Add(p_right);
 }
References GPM::Matrix4< T >::Add().
Add() [7/8]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Add (const Matrix4< U > & p_other)
Definition at line 364 of file Matrix4.inl.
 {
     for (int i = 0; i < 16; i++)
     {
         m_data[i] += p_other.m_data[i];
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Add() [8/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Add (const Matrix4< T > & p_left, const Matrix4< U > & p_right)
Definition at line 376 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Add(p_right);
 }
References GPM::Matrix4< T >::Add().
Adjugate() [1/2]
template<typename T> constexpr Matrix4<T> GPM::Matrix4< T >::Adjugate ()
Referenced by GPM::Matrix4< T >::CreateAdjugate().
Adjugate() [2/2]
template<typename T> constexpr Matrix4< T > Matrix4::Adjugate ()
Definition at line 225 of file Matrix4.inl.
 {
     Matrix4<T> tmpMat(m_data);
     tmpMat.m_data[0] =   GetMinor({ m_data[5], m_data[6], m_data[7], m_data[9], m_data[10], m_data[11], m_data[13], m_data[14], m_data[15] });
     tmpMat.m_data[4] =  -GetMinor({ m_data[4], m_data[6], m_data[7], m_data[8], m_data[10], m_data[11], m_data[12], m_data[14], m_data[15] });
     tmpMat.m_data[8] =   GetMinor({ m_data[4], m_data[5], m_data[7], m_data[8], m_data[9], m_data[11], m_data[12], m_data[13], m_data[15] });
     tmpMat.m_data[12] = -GetMinor({ m_data[4], m_data[5], m_data[6], m_data[8], m_data[9], m_data[10], m_data[12], m_data[13], m_data[14] });
     tmpMat.m_data[1] =  -GetMinor({ m_data[1], m_data[2], m_data[3], m_data[9], m_data[10], m_data[11], m_data[13], m_data[14], m_data[15] });
     tmpMat.m_data[5] =   GetMinor({ m_data[0], m_data[2], m_data[3], m_data[8], m_data[10], m_data[11], m_data[12], m_data[14], m_data[15] });
     tmpMat.m_data[9] =  -GetMinor({ m_data[0], m_data[1], m_data[3], m_data[8], m_data[9], m_data[11], m_data[12], m_data[13], m_data[15] });
     tmpMat.m_data[13] =  GetMinor({ m_data[0], m_data[1], m_data[2], m_data[8], m_data[9], m_data[10], m_data[12], m_data[13], m_data[14] });
     tmpMat.m_data[2] =   GetMinor({ m_data[1], m_data[2], m_data[3], m_data[5], m_data[6], m_data[7], m_data[13], m_data[14], m_data[15] });
     tmpMat.m_data[6] =  -GetMinor({ m_data[0], m_data[2], m_data[3], m_data[4], m_data[6], m_data[7], m_data[12], m_data[14], m_data[15] });
     tmpMat.m_data[10] =  GetMinor({ m_data[0], m_data[1], m_data[3], m_data[4], m_data[5], m_data[7], m_data[12], m_data[13], m_data[15] });
     tmpMat.m_data[14] = -GetMinor({ m_data[0], m_data[1], m_data[2], m_data[4], m_data[5], m_data[6], m_data[12], m_data[13], m_data[14] });
     tmpMat.m_data[3] =  -GetMinor({ m_data[1], m_data[2], m_data[3], m_data[5], m_data[6], m_data[7], m_data[9], m_data[10], m_data[11] });
     tmpMat.m_data[7] =   GetMinor({ m_data[0], m_data[2], m_data[3], m_data[4], m_data[6], m_data[7], m_data[8], m_data[10], m_data[11] });
     tmpMat.m_data[11] = -GetMinor({ m_data[0], m_data[1], m_data[3], m_data[4], m_data[5], m_data[7], m_data[8], m_data[9], m_data[11] });
     tmpMat.m_data[15] =  GetMinor({ m_data[0], m_data[1], m_data[2], m_data[4], m_data[5], m_data[6], m_data[8], m_data[9], m_data[10] });
     return { tmpMat};
 }
References GPM::Matrix4< T >::m_data.
CreateAdjugate() [1/2]
template<typename T> static constexpr Matrix4<T> GPM::Matrix4< T >::CreateAdjugate (const Matrix4< T > & p_matrix) static
CreateAdjugate() [2/2]
template<typename T> constexpr Matrix4< T > Matrix4::CreateAdjugate (const Matrix4< T > & p_matrix) static
Definition at line 253 of file Matrix4.inl.
 {
     return Matrix4<T>(p_matrix).Adjugate();
 }
References GPM::Matrix4< T >::Adjugate().
CreateRotation() [1/2]
template<typename T> static constexpr Matrix4<T> GPM::Matrix4< T >::CreateRotation (const Quaternion & p_rotation) static
CreateRotation() [2/2]
template<typename T> constexpr Matrix4< T > Matrix4::CreateRotation (const Quaternion & p_rotation) static
Definition at line 175 of file Matrix4.inl.
 {
     return p_rotation.ToMatrix4();
 }
References GPM::Quaternion::ToMatrix4().
CreateScale() [1/4]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::CreateScale (const Vector3< U > & p_scale) static
CreateScale() [2/4]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::CreateScale (const Vector3< U > & p_scale) static
CreateScale() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::CreateScale (const Vector3< U > & p_scale)
Definition at line 156 of file Matrix4.inl.
 {
     Matrix4<T> tmpScale = identity;
     tmpScale.m_data[0] = p_scale.x;
     tmpScale.m_data[5] = p_scale.y;
     tmpScale.m_data[10] = p_scale.z;
     return tmpScale;
 }
References GPM::Matrix4< T >::m_data, GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
CreateScale() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::CreateScale (const Vector3< U > & p_scale)
Definition at line 156 of file Matrix4.inl.
 {
     Matrix4<T> tmpScale = identity;
     tmpScale.m_data[0] = p_scale.x;
     tmpScale.m_data[5] = p_scale.y;
     tmpScale.m_data[10] = p_scale.z;
     return tmpScale;
 }
References GPM::Matrix4< T >::m_data, GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
CreateTransformation() [1/4]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::CreateTransformation (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale) static
CreateTransformation() [2/4]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::CreateTransformation (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale) static
CreateTransformation() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::CreateTransformation (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale)
Definition at line 213 of file Matrix4.inl.
 {
     Matrix4<T> tmpTrans = CreateTranslation(p_translate);
     Matrix4<T> tmpRot = CreateRotation(p_rotation);
     Matrix4<T> tmpScale = CreateScale(p_scale);
     Matrix4<T> tmpMat = tmpTrans * tmpRot * tmpScale;
     return tmpMat;
 }
CreateTransformation() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::CreateTransformation (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale)
Definition at line 213 of file Matrix4.inl.
 {
     Matrix4<T> tmpTrans = CreateTranslation(p_translate);
     Matrix4<T> tmpRot = CreateRotation(p_rotation);
     Matrix4<T> tmpScale = CreateScale(p_scale);
     Matrix4<T> tmpMat = tmpTrans * tmpRot * tmpScale;
     // tmpTrans *= tmpRot;
     //tmpMat *= tmpScale;
     return tmpMat;
 }
CreateTranslation() [1/4]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::CreateTranslation (const Vector3< U > & p_translate) static
CreateTranslation() [2/4]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::CreateTranslation (const Vector3< U > & p_translate) static
CreateTranslation() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::CreateTranslation (const Vector3< U > & p_translate)
Definition at line 191 of file Matrix4.inl.
 {
     Matrix4<T> tmpTrans = identity;
     tmpTrans.m_data[3] = p_translate.x;
     tmpTrans.m_data[7] = p_translate.y;
     tmpTrans.m_data[11] = p_translate.z;
     return tmpTrans;
 }
References GPM::Matrix4< T >::m_data, GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
CreateTranslation() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::CreateTranslation (const Vector3< U > & p_translate)
Definition at line 191 of file Matrix4.inl.
 {
     Matrix4<T> tmpTrans = identity;
     tmpTrans.m_data[3] = p_translate.x;
     tmpTrans.m_data[7] = p_translate.y;
     tmpTrans.m_data[11] = p_translate.z;
     return tmpTrans;
 }
References GPM::Matrix4< T >::m_data, GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
Determinant() [1/4]
template<typename T> constexpr T GPM::Matrix4< T >::Determinant ()
Referenced by GPM::Matrix4< T >::Determinant().
Determinant() [2/4]
template<typename T> constexpr T Matrix4::Determinant ()
Definition at line 78 of file Matrix4.inl.
 {
     return ((m_data[0] * GetMinor({ m_data[5], m_data[6], m_data[7], m_data[9], m_data[10], m_data[11], m_data[13], m_data[14], m_data[15] }))
           - (m_data[1] * GetMinor({ m_data[4], m_data[6], m_data[7], m_data[8], m_data[10], m_data[11], m_data[12], m_data[14], m_data[15] }))
           + (m_data[2] * GetMinor({ m_data[4], m_data[5], m_data[7], m_data[8], m_data[9], m_data[11], m_data[12], m_data[13], m_data[15] }))
           - (m_data[3] * GetMinor({ m_data[4], m_data[5], m_data[6], m_data[8], m_data[9], m_data[10], m_data[12], m_data[13], m_data[14] })));
 }
Determinant() [3/4]
template<typename T> static constexpr T GPM::Matrix4< T >::Determinant (const Matrix4< T > & p_matrix) static
Determinant() [4/4]
template<typename T> constexpr T Matrix4::Determinant (const Matrix4< T > & p_matrix) static
Definition at line 87 of file Matrix4.inl.
 {
     return Matrix4<T>(p_matrix).Determinant();
 }
References GPM::Matrix4< T >::Determinant().
Equals() [1/2]
template<typename T> bool GPM::Matrix4< T >::Equals (const Matrix4< T > & p_other)
Equals() [2/2]
template<typename T> bool Matrix4::Equals (const Matrix4< T > & p_other)
Definition at line 544 of file Matrix4.inl.
 {
     for (int i = 0; i < 16; i++)
     {
         if (m_data[i] != p_other.m_data[i])
             return false;
     }
     return true;
 }
References GPM::Matrix4< T >::m_data.
GetMinor() [1/2]
template<typename T> T Matrix4::GetMinor (Matrix3< T > p_minor) static
Definition at line 306 of file Matrix4.inl.
 {
     return ((p_minor.m_data[0] * ((p_minor.m_data[4] * p_minor.m_data[8]) - (p_minor.m_data[5] * p_minor.m_data[7])))
           - (p_minor.m_data[1] * ((p_minor.m_data[3] * p_minor.m_data[8]) - (p_minor.m_data[5] * p_minor.m_data[6])))
           + (p_minor.m_data[2] * ((p_minor.m_data[3] * p_minor.m_data[7]) - (p_minor.m_data[4] * p_minor.m_data[6]))));
 }
References GPM::Matrix3< T >::m_data.
GetMinor() [2/2]
template<typename T> static T GPM::Matrix4< T >::GetMinor (Matrix3< T > p_minor) static
Inverse() [1/2]
template<typename T> constexpr Matrix4< T > Matrix4::Inverse (const Matrix4< T > & p_matrix) static
Definition at line 260 of file Matrix4.inl.
 {
     static_assert(!std::is_integral<T>::value, "Matrix3::CreateTransformation : Can't do Transform Matrices with Matrix3<int>, as values would be rounded to 0");
     Matrix4<T> tmpMat;
     const Matrix4<T> Adj = CreateAdjugate(p_matrix);
     const T Det = Determinant(p_matrix);
     for (int i = 0; i < 16; ++i)
     {
         tmpMat.m_data[i] = Adj.m_data[i] / Det;
     }
     return tmpMat;
 }
References GPM::Matrix4< T >::m_data.
Inverse() [2/2]
template<typename T> static constexpr Matrix4<T> GPM::Matrix4< T >::Inverse (const Matrix4< T > & p_matrix) static
isIdentity() [1/2]
template<typename T> constexpr bool GPM::Matrix4< T >::isIdentity ()
isIdentity() [2/2]
template<typename T> constexpr bool Matrix4::isIdentity ()
Definition at line 72 of file Matrix4.inl.
 {
     return Equals(identity);
 }
LookAt() [1/2]
template<typename T> static Matrix4<T> GPM::Matrix4< T >::LookAt (const Vector3< T > & p_from, const Vector3< T > & p_to, const Vector3< T > & p_up = { 0, 1, 0 }) static
LookAt() [2/2]
template<typename T> static Matrix4<T> GPM::Matrix4< T >::LookAt (const Vector3< T > & p_from, const Vector3< T > & p_to, const Vector3< T > & p_up = { 0, 1, 0 }) static
Multiply() [1/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (U p_scalar)
Multiply scalar to elements.
Parameters
p_scalar : The value you want to scale the matrix with
Returns
The current Matrix modified
Referenced by GPM::Matrix4< T >::Multiply(), and GPM::Matrix4< T >::operator *().
Multiply() [2/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (U p_scalar)
Multiply scalar to elements.
Parameters
p_scalar : The value you want to scale the matrix with
Returns
The current Matrix modified
Multiply() [3/24]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, U p_right) static
Multiply scalar to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this scalar to the other parameter
Returns
The copy of the Matrix operation result
Multiply() [4/24]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, U p_right) static
Multiply scalar to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this scalar to the other parameter
Returns
The copy of the Matrix operation result
Multiply() [5/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_other)
Multiply matrix with another matrix.
Parameters
p_other : The matrix you want to use as a scalar
Returns
The current Matrix modified
Multiply() [6/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_other)
Multiply matrix with another matrix.
Parameters
p_other : The matrix you want to use as a scalar
Returns
The current Matrix modified
Multiply() [7/24]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, const Matrix4< U > & p_right) static
Multiply matrix to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this matrix to the other parameter
Returns
The copy of the Matrix operation result
Multiply() [8/24]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, const Matrix4< U > & p_right) static
Multiply matrix to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this matrix to the other parameter
Returns
The copy of the Matrix operation result
Multiply() [9/24]
template<typename T> template<typename U > Vector4<U>& GPM::Matrix4< T >::Multiply (const Vector4< U > & p_other)
Multiply() [10/24]
template<typename T> template<typename U > Vector4<U>& GPM::Matrix4< T >::Multiply (const Vector4< U > & p_other)
Multiply() [11/24]
template<typename T> template<typename U > static Vector4<T> GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_matrix, const Vector4< T > & p_vector) static
Multiply() [12/24]
template<typename T> template<typename U > static Vector4<T> GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_matrix, const Vector4< T > & p_vector) static
Multiply() [13/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (U p_scalar)
Definition at line 420 of file Matrix4.inl.
 {
     for (unsigned int i = 0; i < 16; ++i)
     {
         m_data[i] *= p_scalar;
     }
     return { *this };
 }
Multiply() [14/24]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, U p_right)
Definition at line 432 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Multiply(p_right);
 }
References GPM::Matrix4< T >::Multiply().
Multiply() [15/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (U p_scalar)
Definition at line 439 of file Matrix4.inl.
 {
     for (unsigned int i = 0; i < 16; ++i)
     {
         m_data[i] *= p_scalar;
     }
     return { *this };
 }
Multiply() [16/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_other)
Definition at line 440 of file Matrix4.inl.
 {
     Matrix4<T> tmpMat(this->m_data);
     for (int i = 0; i < 16; i += 4)
     {
         for (int j = 0; j < 4; j++)
         {
             m_data[i + j] = (tmpMat.m_data[i] * p_other.m_data[j])
                           + (tmpMat.m_data[i + 1] * p_other.m_data[j + 4])
                           + (tmpMat.m_data[i + 2] * p_other.m_data[j + 8])
                           + (tmpMat.m_data[i + 3] * p_other.m_data[j + 12]);
         }
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Multiply() [17/24]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, U p_right)
Definition at line 451 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Multiply(p_right);
 }
References GPM::Matrix4< T >::Multiply().
Multiply() [18/24]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_other)
Definition at line 459 of file Matrix4.inl.
 {
     Matrix4<T> tmpMat(this->m_data);
     for (int i = 0; i < 16; i += 4)
     {
         for (int j = 0; j < 4; j++)
         {
             m_data[i + j] = (tmpMat.m_data[i] * p_other.m_data[j])
                           + (tmpMat.m_data[i + 1] * p_other.m_data[j + 4])
                           + (tmpMat.m_data[i + 2] * p_other.m_data[j + 8])
                           + (tmpMat.m_data[i + 3] * p_other.m_data[j + 12]);
         }
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Multiply() [19/24]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, const Matrix4< U > & p_right)
Definition at line 460 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Multiply(p_right);
 }
References GPM::Matrix4< T >::Multiply().
Multiply() [20/24]
template<typename T> template<typename U > Vector4<U>& GPM::Matrix4< T >::Multiply (const Vector4< U > & p_other)
Definition at line 467 of file Matrix4.inl.
 {
     Vector4<T> tmpVec = Vector4F::zero;
     tmpVec.x = (m_data[0] * p_other.x)
         + (m_data[1] * p_other.y)
         + (m_data[2] * p_other.z)
         + (m_data[3] * p_other.w);
     tmpVec.y = (m_data[4] * p_other.x)
         + (m_data[5] * p_other.y)
         + (m_data[6] * p_other.z)
         + (m_data[7] * p_other.w);
     tmpVec.z = (m_data[8] * p_other.x)
         + (m_data[9] * p_other.y)
         + (m_data[10] * p_other.z)
         + (m_data[11] * p_other.w);
     tmpVec.w = (m_data[12] * p_other.x)
         + (m_data[13] * p_other.y)
         + (m_data[14] * p_other.z)
         + (m_data[15] * p_other.w);
     return tmpVec;
 }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, GPM::Vector4< T >::z, and GPM::Vector4< T >::zero.
Multiply() [21/24]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Multiply (const Matrix4< T > & p_left, const Matrix4< U > & p_right)
Definition at line 479 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Multiply(p_right);
 }
References GPM::Matrix4< T >::Multiply().
Multiply() [22/24]
template<typename T> template<typename U > Vector4<U>& GPM::Matrix4< T >::Multiply (const Vector4< U > & p_other)
Definition at line 486 of file Matrix4.inl.
 {
     Vector4<T> tmpVec = Vector4F::zero;
     tmpVec.x = (m_data[0] * p_other.x)
         + (m_data[1] * p_other.y)
         + (m_data[2] * p_other.z)
         + (m_data[3] * p_other.w);
     tmpVec.y = (m_data[4] * p_other.x)
         + (m_data[5] * p_other.y)
         + (m_data[6] * p_other.z)
         + (m_data[7] * p_other.w);
     tmpVec.z = (m_data[8] * p_other.x)
         + (m_data[9] * p_other.y)
         + (m_data[10] * p_other.z)
         + (m_data[11] * p_other.w);
     tmpVec.w = (m_data[12] * p_other.x)
         + (m_data[13] * p_other.y)
         + (m_data[14] * p_other.z)
         + (m_data[15] * p_other.w);
     return tmpVec;
 }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, GPM::Vector4< T >::z, and GPM::Vector4< T >::zero.
Multiply() [23/24]
template<typename T> template<typename U > Vector4<T> GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_matrix, const Vector4< T > & p_vector)
Definition at line 516 of file Matrix4.inl.
 {
     Vector4<T> tmpVec = Vector4F::zero;
     tmpVec.x = (p_matrix[0] * p_vector.x)
         + (p_matrix[1] * p_vector.y)
         + (p_matrix[2] * p_vector.z)
         + (p_matrix[3] * p_vector.w);
     tmpVec.y = (p_matrix[4] * p_vector.x)
         + (p_matrix[5] * p_vector.y)
         + (p_matrix[6] * p_vector.z)
         + (p_matrix[7] * p_vector.w);
     tmpVec.z = (p_matrix[8] * p_vector.x)
         + (p_matrix[9] * p_vector.y)
         + (p_matrix[10] * p_vector.z)
         + (p_matrix[11] * p_vector.w);
     tmpVec.w = (p_matrix[12] * p_vector.x)
         + (p_matrix[13] * p_vector.y)
         + (p_matrix[14] * p_vector.z)
         + (p_matrix[15] * p_vector.w);
     return tmpVec;
 }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, GPM::Vector4< T >::z, and GPM::Vector4< T >::zero.
Multiply() [24/24]
template<typename T> template<typename U > Vector4<T> GPM::Matrix4< T >::Multiply (const Matrix4< U > & p_matrix, const Vector4< T > & p_vector)
Definition at line 535 of file Matrix4.inl.
 {
     Vector4<T> tmpVec = Vector4F::zero;
     tmpVec.x = (p_matrix[0] * p_vector.x)
         + (p_matrix[1] * p_vector.y)
         + (p_matrix[2] * p_vector.z)
         + (p_matrix[3] * p_vector.w);
     tmpVec.y = (p_matrix[4] * p_vector.x)
         + (p_matrix[5] * p_vector.y)
         + (p_matrix[6] * p_vector.z)
         + (p_matrix[7] * p_vector.w);
     tmpVec.z = (p_matrix[8] * p_vector.x)
         + (p_matrix[9] * p_vector.y)
         + (p_matrix[10] * p_vector.z)
         + (p_matrix[11] * p_vector.w);
     tmpVec.w = (p_matrix[12] * p_vector.x)
         + (p_matrix[13] * p_vector.y)
         + (p_matrix[14] * p_vector.z)
         + (p_matrix[15] * p_vector.w);
     return tmpVec;
 }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, GPM::Vector4< T >::z, and GPM::Vector4< T >::zero.
Normalize() [1/4]
template<typename T> constexpr Matrix4<T>& GPM::Matrix4< T >::Normalize ()
Referenced by GPM::Matrix4< T >::Normalize().
Normalize() [2/4]
template<typename T> constexpr Matrix4< T > & Matrix4::Normalize ()
Definition at line 126 of file Matrix4.inl.
 {
     T det = Determinant();
     for (auto& i : m_data)
     {
         i /= det;
     }
     return { *this };
 }
Normalize() [3/4]
template<typename T> constexpr Matrix4< T > Matrix4::Normalize (const Matrix4< T > & p_matrix) static
Definition at line 139 of file Matrix4.inl.
 {
     return p_matrix.Normalize();
 }
References GPM::Matrix4< T >::Normalize().
Normalize() [4/4]
template<typename T> static constexpr Matrix4<T> GPM::Matrix4< T >::Normalize (const Matrix4< T > & p_matrix) static
operator *() [1/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator * (const Matrix4< U > & p_other) const
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The copy of the Matrix operation result
operator *() [2/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator * (const Matrix4< U > & p_other) const
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The copy of the Matrix operation result
operator *() [3/8]
template<typename T> Vector4<T> GPM::Matrix4< T >::operator * (const Vector4< T > & p_vector)
operator *() [4/8]
template<typename T> Vector4<T> GPM::Matrix4< T >::operator * (const Vector4< T > & p_vector)
operator *() [5/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator * (const Matrix4< U > & p_other) const
Definition at line 497 of file Matrix4.inl.
 {
     return Matrix4<T>(*this).Multiply(p_other) ;
 }
References GPM::Matrix4< T >::Multiply().
operator *() [6/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator * (const Matrix4< U > & p_other) const
Definition at line 516 of file Matrix4.inl.
 {
     return Matrix4<T>(*this).Multiply(p_other) ;
 }
References GPM::Matrix4< T >::Multiply().
operator *() [7/8]
template<typename T> template<typename T > Vector4<T> GPM::Matrix4< T >::operator * (const Vector4< T > & p_vector)
Definition at line 568 of file Matrix4.inl.
 {
     return Matrix4<T>(*this).Multiply(p_vector);
 }
References GPM::Matrix4< T >::Multiply().
operator *() [8/8]
template<typename T> template<typename T > Vector4<T> GPM::Matrix4< T >::operator * (const Vector4< T > & p_vector)
Definition at line 587 of file Matrix4.inl.
 {
     return Matrix4<T>(*this).Multiply(p_vector);
 }
References GPM::Matrix4< T >::Multiply().
operator *=() [1/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator *= (const Matrix4< U > & p_other)
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The current Matrix modified
operator *=() [2/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator *= (const Matrix4< U > & p_other)
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The current Matrix modified
operator *=() [3/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator *= (const Matrix4< U > & p_other)
Definition at line 504 of file Matrix4.inl.
 {
     return Multiply(p_other);
 }
operator *=() [4/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator *= (const Matrix4< U > & p_other)
Definition at line 523 of file Matrix4.inl.
 {
     return Multiply(p_other);
 }
operator!=() [1/2]
template<typename T> bool GPM::Matrix4< T >::operator!= (const Matrix4< T > & p_matrix)
operator!=() [2/2]
template<typename T> bool Matrix4::operator!= (const Matrix4< T > & p_matrix)
Definition at line 580 of file Matrix4.inl.
 {
     return !Equals(p_matrix);
 }
operator+() [1/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator+ (const Matrix4< U > & p_other) const
Return the summation of other matrix and current matrix.
Parameters
p_other : The other matrix you want to add
Returns
The copy of the Matrix operation result
operator+() [2/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator+ (const Matrix4< U > & p_other) const
Return the summation of other matrix and current matrix.
Parameters
p_other : The other matrix you want to add
Returns
The copy of the Matrix operation result
operator+() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator+ (const Matrix4< U > & p_other) const
Definition at line 364 of file Matrix4.inl.
 {
     return Add(this, p_other);
 }
operator+() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator+ (const Matrix4< U > & p_other) const
Definition at line 383 of file Matrix4.inl.
 {
     return Add(this, p_other);
 }
operator+=() [1/4]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::operator+= (const Matrix4< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
operator+=() [2/4]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::operator+= (const Matrix4< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
operator+=() [3/4]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::operator+= (const Matrix4< U > & p_other)
Definition at line 371 of file Matrix4.inl.
 {
     return Add(p_other);
 }
operator+=() [4/4]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::operator+= (const Matrix4< U > & p_other)
Definition at line 390 of file Matrix4.inl.
 {
     return Add(p_other);
 }
operator-() [1/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator- (const Matrix4< U > & p_other) const
Return the subtraction of other matrix and current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The copy of the Matrix operation result
operator-() [2/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator- (const Matrix4< U > & p_other) const
Return the subtraction of other matrix and current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The copy of the Matrix operation result
operator-() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator- (const Matrix4< U > & p_other) const
Definition at line 401 of file Matrix4.inl.
 {
     return Subtract(this, p_other);
 }
operator-() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::operator- (const Matrix4< U > & p_other) const
Definition at line 420 of file Matrix4.inl.
 {
     return Subtract(this, p_other);
 }
operator-=() [1/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator-= (const Matrix4< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
operator-=() [2/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator-= (const Matrix4< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
operator-=() [3/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator-= (const Matrix4< U > & p_other)
Definition at line 408 of file Matrix4.inl.
 {
     return Subtract(p_other);
 }
operator-=() [4/4]
template<typename T> template<typename U > Matrix4<T>& GPM::Matrix4< T >::operator-= (const Matrix4< U > & p_other)
Definition at line 427 of file Matrix4.inl.
 {
     return Subtract(p_other);
 }
operator=() [1/4]
template<typename T> template<typename U > void GPM::Matrix4< T >::operator= (const Matrix4< U > & p_matrix)
operator=() [2/4]
template<typename T> template<typename U > void GPM::Matrix4< T >::operator= (const Matrix4< U > & p_matrix)
operator=() [3/4]
template<typename T> template<typename U > void GPM::Matrix4< T >::operator= (const Matrix4< U > & p_matrix)
Definition at line 587 of file Matrix4.inl.
 {
     Set(*this, p_matrix);
 }
operator=() [4/4]
template<typename T> template<typename U > void GPM::Matrix4< T >::operator= (const Matrix4< U > & p_matrix)
Definition at line 606 of file Matrix4.inl.
 {
     Set(*this, p_matrix);
 }
operator==() [1/2]
template<typename T> bool Matrix4::operator== (const Matrix4< T > & p_matrix)
Definition at line 574 of file Matrix4.inl.
 {
     return Equals(p_matrix);
 }
operator==() [2/2]
template<typename T> bool GPM::Matrix4< T >::operator== (const Matrix4< T > & p_matrix)
operator[]() [1/2]
template<typename T> T GPM::Matrix4< T >::operator[] (int p_position)
operator[]() [2/2]
template<typename T> T Matrix4::operator[] (int p_position)
Definition at line 593 of file Matrix4.inl.
 {
     return m_data[p_position];
 }
Rotate() [1/2]
template<typename T> constexpr Matrix4< T > & Matrix4::Rotate (const Quaternion & p_rotation)
Definition at line 167 of file Matrix4.inl.
 {
     this *= p_rotation.ToMatrix4();
     return { *this };
 }
References GPM::Quaternion::ToMatrix4().
Rotate() [2/2]
template<typename T> constexpr Matrix4<T>& GPM::Matrix4< T >::Rotate (const Quaternion & p_rotation)
Scale() [1/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Scale (const Vector3< U > & p_scale)
Scale() [2/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Scale (const Vector3< U > & p_scale)
Scale() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Scale (const Vector3< U > & p_scale)
Definition at line 147 of file Matrix4.inl.
 {
     this *= CreateScale(p_scale);
     return { *this };
 }
Scale() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Scale (const Vector3< U > & p_scale)
Definition at line 147 of file Matrix4.inl.
 {
     this *= CreateScale(p_scale);
     return { *this };
 }
Set() [1/4]
template<typename T> template<typename U > static void GPM::Matrix4< T >::Set (Matrix4< T > & p_matrix, const Matrix4< U > & p_other) static
Set() [2/4]
template<typename T> template<typename U > static void GPM::Matrix4< T >::Set (Matrix4< T > & p_matrix, const Matrix4< U > & p_other) static
Set() [3/4]
template<typename T> template<typename U > void GPM::Matrix4< T >::Set (Matrix4< T > & p_matrix, const Matrix4< U > & p_other)
Definition at line 556 of file Matrix4.inl.
 {
     memcpy(p_matrix.m_data, p_other.m_data, sizeof(U) * 16);
 }
References GPM::Matrix4< T >::m_data.
Set() [4/4]
template<typename T> template<typename U > void GPM::Matrix4< T >::Set (Matrix4< T > & p_matrix, const Matrix4< U > & p_other)
Definition at line 575 of file Matrix4.inl.
 {
     memcpy(p_matrix.m_data, p_other.m_data, sizeof(U) * 16);
 }
References GPM::Matrix4< T >::m_data.
SetColumn() [1/2]
template<typename T> constexpr void GPM::Matrix4< T >::SetColumn (int p_column, const Vector4< T > & p_vector)
SetColumn() [2/2]
template<typename T> constexpr void Matrix4::SetColumn (int p_column, const Vector4< T > & p_vector)
Definition at line 287 of file Matrix4.inl.
 {
     m_data[p_column] = p_vector.x;
     m_data[p_column + 4] = p_vector.y;
     m_data[p_column + 8] = p_vector.z;
     m_data[p_column + 12] = p_vector.w;
 }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
SetRow() [1/2]
template<typename T> constexpr void GPM::Matrix4< T >::SetRow (int p_row, const Vector4< T > & p_vector)
SetRow() [2/2]
template<typename T> constexpr void Matrix4::SetRow (int p_row, const Vector4< T > & p_vector)
Definition at line 296 of file Matrix4.inl.
 {
     int rowStart = (4 * p_row);
     m_data[rowStart] = p_vector.x;
     m_data[rowStart + 1] = p_vector.y;
     m_data[rowStart + 2] = p_vector.z;
     m_data[rowStart + 3] = p_vector.w;
 }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Subtract() [1/8]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
Referenced by GPM::Matrix4< T >::Subtract().
Subtract() [2/8]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
Subtract() [3/8]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< T > & p_left, const Matrix4< U > & p_right) static
Subtract left matrix to the right matrix.
Parameters
p_left : The first matrix you want to subtract to
p_right : The second matrix to be subtracted from the first one
Returns
The copy of the Matrix operation result
Subtract() [4/8]
template<typename T> template<typename U > static constexpr Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< T > & p_left, const Matrix4< U > & p_right) static
Subtract left matrix to the right matrix.
Parameters
p_left : The first matrix you want to subtract to
p_right : The second matrix to be subtracted from the first one
Returns
The copy of the Matrix operation result
Subtract() [5/8]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< U > & p_other)
Definition at line 382 of file Matrix4.inl.
 {
     for (int i = 0; i < 16; i++)
     {
         m_data[i] -= p_other.m_data[i];
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Subtract() [6/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< T > & p_left, const Matrix4< U > & p_right)
Definition at line 394 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Subtract(p_right);
 }
References GPM::Matrix4< T >::Subtract().
Subtract() [7/8]
template<typename T> template<typename U > Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< U > & p_other)
Definition at line 401 of file Matrix4.inl.
 {
     for (int i = 0; i < 16; i++)
     {
         m_data[i] -= p_other.m_data[i];
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Subtract() [8/8]
template<typename T> template<typename U > constexpr Matrix4<T> GPM::Matrix4< T >::Subtract (const Matrix4< T > & p_left, const Matrix4< U > & p_right)
Definition at line 413 of file Matrix4.inl.
 {
     return Matrix4<T>(p_left).Subtract(p_right);
 }
References GPM::Matrix4< T >::Subtract().
ToString() [1/4]
template<typename T> constexpr std::string GPM::Matrix4< T >::ToString () noexcept
ToString() [2/4]
template<typename T> constexpr std::string GPM::Matrix4< T >::ToString () noexcept
ToString() [3/4]
template<typename T> static constexpr std::string GPM::Matrix4< T >::ToString (const Matrix4< T > & p_matrix) static
ToString() [4/4]
template<typename T> constexpr std::string Matrix4::ToString (const Matrix4< T > & p_matrix) static
Definition at line 327 of file Matrix4.inl.
 {
     std::stringstream StringStream;
     StringStream << '[' << p_matrix.m_data[0] << "  " << p_matrix.m_data[1] << "  " << p_matrix.m_data[2] << "  " << p_matrix.m_data[3] << "]\n"
         << '[' << p_matrix.m_data[4] << "  " << p_matrix.m_data[5] << "  " << p_matrix.m_data[6] << "  " << p_matrix.m_data[7] << "]\n"
         << '[' << p_matrix.m_data[8] << "  " << p_matrix.m_data[9] << "  " << p_matrix.m_data[10] << "  " << p_matrix.m_data[11] << "]\n"
         << '[' << p_matrix.m_data[12] << "  " << p_matrix.m_data[13] << "  " << p_matrix.m_data[14] << "  " << p_matrix.m_data[15] << "]\n";
     return { StringStream.str() };
 }
References GPM::Matrix4< T >::m_data.
Transform() [1/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Transform (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale)
Transform() [2/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Transform (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale)
Transform() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Transform (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale)
Definition at line 204 of file Matrix4.inl.
 {
     this *= CreateTransform(p_translate, p_rotation, p_scale);
     return { *this };
 }
Transform() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Transform (const Vector3< U > & p_translate, const Quaternion & p_rotation, const Vector3< U > & p_scale)
Definition at line 204 of file Matrix4.inl.
 {
     this *= CreateTransform(p_translate, p_rotation, p_scale);
     return { *this };
 }
Translate() [1/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Translate (const Vector3< U > & p_translate)
Translate() [2/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Translate (const Vector3< U > & p_translate)
Translate() [3/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Translate (const Vector3< U > & p_translate)
Definition at line 182 of file Matrix4.inl.
 {
     this *= CreateTranslate(p_translate);
     return { *this };
 }
Translate() [4/4]
template<typename T> template<typename U > constexpr Matrix4<T>& GPM::Matrix4< T >::Translate (const Vector3< U > & p_translate)
Definition at line 182 of file Matrix4.inl.
 {
     this *= CreateTranslate(p_translate);
     return { *this };
 }
Transpose() [1/4]
template<typename T> constexpr Matrix4<T>& GPM::Matrix4< T >::Transpose ()
Transpose() [2/4]
template<typename T> constexpr Matrix4< T > & Matrix4::Transpose ()
Definition at line 93 of file Matrix4.inl.
 {
     Matrix4<T> tmpMat(this->m_data);
     for (int n = 0; n < 16; n++)
     {
         int i = n / 4;
         int j = n % 4;
         m_data[n] = tmpMat.m_data[4 * j + i];
     }
     return { *this };
 }
References GPM::Matrix4< T >::m_data.
Transpose() [3/4]
template<typename T> static constexpr Matrix4<T> GPM::Matrix4< T >::Transpose (const Matrix4< T > & p_matrix) static
Transpose() [4/4]
template<typename T> constexpr Matrix4< T > Matrix4::Transpose (const Matrix4< T > & p_matrix) static
Definition at line 110 of file Matrix4.inl.
 {
     Matrix4<T> tmpMat = identity;
     for (int n = 0; n < 16; n++)
     {
         int i = n / 4;
         int j = n % 4;
         tmpMat.m_data[n] = p_matrix.m_data[4 * j + i];
     }
     return tmpMat;
 }
References GPM::Matrix4< T >::m_data.
Field Documentation
identity
template<typename T> Matrix4< T > Matrix4::identity static
Initial value:
= { 1,0,0,0,
                                    0,1,0,0,
                                    0,0,1,0,
                                    0,0,0,1}
This is a const matrix that has 1 in the diagonal and 0 elsewhere.
Definition at line 45 of file Matrix4.h.
m_data
template<typename T> T GPM::Matrix4< T >::m_data
Initial value:
= {
            1, 0, 0, 0,
            0, 1, 0, 0,
            0, 0, 1, 0,
            0, 0, 0, 1
        }
Definition at line 19 of file Matrix4.h.
Referenced by GPM::Matrix4< T >::Add(), GPM::Matrix4< T >::Adjugate(), GPM::Matrix4< T >::CreateScale(), GPM::Matrix4< T >::CreateTranslation(), GPM::Matrix4< T >::Equals(), GPM::Matrix4< T >::Inverse(), GPM::Matrix4< T >::Matrix4(), GPM::Matrix4< T >::Multiply(), GPM::Matrix4< T >::Set(), GPM::Matrix4< T >::Subtract(), GPM::Matrix4< T >::ToString(), and GPM::Matrix4< T >::Transpose().
zero
template<typename T> Matrix4< T > Matrix4::zero static
Initial value:
= { 0,0,0,0,
                                0,0,0,0,
                                0,0,0,0,
                                0,0,0,0 }
This is a const matrix that has 0 everywhere.
Definition at line 50 of file Matrix4.h.
The documentation for this struct was generated from the following files:
GPM/include/GPM/Matrix/Matrix4.h
GPM/include/GPM/Matrix/Matrix4.inl