GPM: GPM::Matrix3< T > Struct Template Reference
GPM::Matrix3< T > Struct Template Reference
#include <Matrix3.h>
Public Member Functions
constexpr Matrix3 ()
Default Constructor.
~Matrix3 ()=default
Default Destructor.
constexpr Matrix3 (const T p_i0, const T p_i1, const T p_i2, const T p_i3, const T p_i4, const T p_i5, const T p_i6, const T p_i7, const T p_i8)
Constructor with parameters.
constexpr Matrix3 (const T p_data[9])
Constructor from already created array.
constexpr Matrix3 (const Matrix3 &p_other)
Copy Constructor.
template<typename U >
constexpr Matrix3 (const Matrix3< U > &p_other)
Template Copy Constructor.
constexpr Matrix3 (Matrix3 &&p_other) noexcept
Move Constructor.
constexpr Matrix3< T > & operator= (const Matrix3< T > &p_other)
Assignment operator for Matrix3.
template<typename U >
constexpr Matrix3< T > & operator= (const Matrix3< U > &p_other)
Assignment operator for Matrix3.
constexpr Matrix3< T > & operator= (Matrix3< T > &&p_other) noexcept
Assignment move operator for Matrix3.
template<typename U >
constexpr Matrix3< T > & operator= (Matrix3< U > &&p_other) noexcept
Assignment move operator for Matrix3.
T Determinant ()
Calculates the determinant of the matrix.
constexpr Matrix3< T > & Transpose ()
Returns this matrix transposed.
constexpr Vector3< T > GetColumn (const int p_column)
Attempts to retrieve a column from the matrix.
template<typename U >
constexpr void SetColumn (const int p_column, const Vector3< U > &p_vector)
Attempts to set a column in the matrix.
constexpr Vector3< T > GetRow (const int p_row)
Attempts to retrieve a row from the matrix.
template<typename U >
constexpr void SetRow (const int p_row, const Vector3< U > &p_vector)
Attempts to set a row in the matrix.
constexpr Matrix3< T > & Normalize ()
Returns this matrix with a magnitude of 1.
template<typename U >
constexpr Matrix3< T > & Translate (const Vector2< U > &p_vector)
Translates the current matrix with a Vector2.
constexpr Matrix3< T > & Rotate (const float p_angle)
Rotate the current matrix with an angle in degrees.
template<typename U >
constexpr Matrix3< T > & Scale (const Vector2< U > &p_vector)
Scale the current matrix with a Vector2.
template<typename U >
constexpr Matrix3< T > & LookAt (const Vector3< U > &p_dir, const Vector3< U > &p_up, Matrix3< T > &p_matrix)
Computes a transformation matrix that looks at a target.
template<typename U >
Matrix3< T > & Add (const Matrix3< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
constexpr Matrix3< T > operator+ (const Matrix3< U > &p_other) const
Return the summation of other matrix and current matrix.
template<typename U >
Matrix3< T > & operator+= (const Matrix3< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
Matrix3< T > & Subtract (const Matrix3< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
constexpr Matrix3< T > operator- (const Matrix3< U > &p_other) const
Return the subtraction of other matrix and current matrix.
template<typename U >
Matrix3< T > & operator -= (const Matrix3< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
Matrix3< T > & Multiply (U p_scalar)
Multiply scalar to elements.
template<typename U >
Matrix3< T > & Multiply (const Matrix3< U > &p_other)
Multiply matrix with another matrix.
template<class U >
constexpr Matrix3< T > operator * (const Matrix3< U > &p_other) const
Multiply matrix to the current matrix.
template<class U >
constexpr Matrix3< T > operator * (const U p_scalar) const
Multiply matrix to the current matrix.
template<class U >
Matrix3< T > & operator *= (const U p_scalar)
Multiply matrix to the current matrix.
template<class U >
Matrix3< T > & operator *= (const Matrix3< U > &p_other)
Multiply matrix to the current matrix.
template<typename U >
Matrix3< T > & Divide (U p_scalar)
Divide elements by scalar.
template<class U >
constexpr Matrix3< T > operator/ (const U p_scalar) const
Divide matrix p_left by scalar.
template<class U >
Matrix3< T > & operator/= (const U p_scalar)
Divide elements by scalar.
constexpr bool Equals (const Matrix3< T > &p_other) const
Return true if the two matrices are identical.
constexpr bool operator== (const Matrix3< T > &p_other) const
Return true if the two matrices are identical.
constexpr bool operator!= (const Matrix3< T > &p_other) const
Return true if the two matrices are different.
constexpr std::string ToString ()
function used to debug values from the matrix
constexpr Matrix3 ()
Default Constructor.
~Matrix3 ()=default
Default Destructor.
constexpr Matrix3 (const T p_i0, const T p_i1, const T p_i2, const T p_i3, const T p_i4, const T p_i5, const T p_i6, const T p_i7, const T p_i8)
Constructor with parameters.
constexpr Matrix3 (const T p_data[9])
Constructor from already created array.
constexpr Matrix3 (const Matrix3 &p_other)
Copy Constructor.
template<typename U >
constexpr Matrix3 (const Matrix3< U > &p_other)
Template Copy Constructor.
constexpr Matrix3 (Matrix3 &&p_other) noexcept
Move Constructor.
constexpr Matrix3< T > & operator= (const Matrix3< T > &p_other)
Assignment operator for Matrix3.
template<typename U >
constexpr Matrix3< T > & operator= (const Matrix3< U > &p_other)
Assignment operator for Matrix3.
constexpr Matrix3< T > & operator= (Matrix3< T > &&p_other) noexcept
Assignment move operator for Matrix3.
template<typename U >
constexpr Matrix3< T > & operator= (Matrix3< U > &&p_other) noexcept
Assignment move operator for Matrix3.
T Determinant ()
Calculates the determinant of the matrix.
constexpr Matrix3< T > & Transpose ()
Returns this matrix transposed.
constexpr Vector3< T > GetColumn (const int p_column)
Attempts to retrieve a column from the matrix.
template<typename U >
constexpr void SetColumn (const int p_column, const Vector3< U > &p_vector)
Attempts to set a column in the matrix.
constexpr Vector3< T > GetRow (const int p_row)
Attempts to retrieve a row from the matrix.
template<typename U >
constexpr void SetRow (const int p_row, const Vector3< U > &p_vector)
Attempts to set a row in the matrix.
constexpr Matrix3< T > & Normalize ()
Returns this matrix with a magnitude of 1.
template<typename U >
constexpr Matrix3< T > & Translate (const Vector2< U > &p_vector)
Translates the current matrix with a Vector2.
constexpr Matrix3< T > & Rotate (const float p_angle)
Rotate the current matrix with an angle in degrees.
template<typename U >
constexpr Matrix3< T > & Scale (const Vector2< U > &p_vector)
Scale the current matrix with a Vector2.
template<typename U >
constexpr Matrix3< T > & LookAt (const Vector3< U > &p_dir, const Vector3< U > &p_up, Matrix3< T > &p_matrix)
Computes a transformation matrix that looks at a target.
template<typename U >
Matrix3< T > & Add (const Matrix3< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
constexpr Matrix3< T > operator+ (const Matrix3< U > &p_other) const
Return the summation of other matrix and current matrix.
template<typename U >
Matrix3< T > & operator+= (const Matrix3< U > &p_other)
Add other matrix to the current matrix.
template<typename U >
Matrix3< T > & Subtract (const Matrix3< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
constexpr Matrix3< T > operator- (const Matrix3< U > &p_other) const
Return the subtraction of other matrix and current matrix.
template<typename U >
Matrix3< T > & operator -= (const Matrix3< U > &p_other)
Subtract other matrix to the current matrix.
template<typename U >
Matrix3< T > & Multiply (U p_scalar)
Multiply scalar to elements.
template<typename U >
Matrix3< T > & Multiply (const Matrix3< U > &p_other)
Multiply matrix with another matrix.
template<class U >
constexpr Matrix3< T > operator * (const Matrix3< U > &p_other) const
Multiply matrix to the current matrix.
template<class U >
constexpr Matrix3< T > operator * (const U p_scalar) const
Multiply matrix to the current matrix.
template<class U >
Matrix3< T > & operator *= (const U p_scalar)
Multiply matrix to the current matrix.
template<class U >
Matrix3< T > & operator *= (const Matrix3< U > &p_other)
Multiply matrix to the current matrix.
template<typename U >
Matrix3< T > & Divide (U p_scalar)
Divide elements by scalar.
template<class U >
constexpr Matrix3< T > operator/ (const U p_scalar) const
Divide matrix p_left by scalar.
template<class U >
Matrix3< T > & operator/= (const U p_scalar)
Divide elements by scalar.
constexpr bool Equals (const Matrix3< T > &p_other) const
Return true if the two matrices are identical.
constexpr bool operator== (const Matrix3< T > &p_other) const
Return true if the two matrices are identical.
constexpr bool operator!= (const Matrix3< T > &p_other) const
Return true if the two matrices are different.
constexpr std::string ToString ()
function used to debug values from the matrix
Static Public Member Functions
static T Determinant (const Matrix3< T > &p_matrix3)
Calculates the determinant of the matrix.
static constexpr Matrix3< T > Transpose (const Matrix3< T > &p_matrix3)
Returns this matrix transposed.
static constexpr Matrix3< T > Normalize (const Matrix3< T > &p_matrix)
Returns this matrix with a magnitude of 1.
template<typename U >
static constexpr Matrix3< T > CreateTranslation (const Vector2< U > &p_vector)
Creates a translation identity matrix with a Vector2 offset.
static constexpr Matrix3< T > CreateRotation (const float p_angle)
Creates a rotation identity matrix with an angle in degrees.
template<typename U >
static constexpr Matrix3< T > CreateScaling (const Vector2< U > &p_vector)
Creates a scaling identity matrix with a Vector2.
template<typename U >
static constexpr Matrix3< T > CreateTransformation (const Vector2< U > &p_pos, const float p_angle, const Vector2< U > &p_scale)
Creates a translation, rotation and scaling matrix.
template<typename U >
static constexpr Matrix3< T > Add (const Matrix3< T > &p_left, const Matrix3< U > &p_right)
Add left matrix to the right matrix.
template<typename U >
static constexpr Matrix3< T > Subtract (const Matrix3< T > &p_left, const Matrix3< U > &p_right)
Subtract left matrix to the right matrix.
template<typename U >
static constexpr Matrix3< T > Multiply (const Matrix3< T > &p_left, U p_scalar)
Multiply scalar to matrix left.
template<typename U >
static constexpr Matrix3< T > Multiply (const Matrix3< T > &p_left, const Matrix3< U > &p_right)
Multiply scalar to matrix left.
template<typename U >
static constexpr Matrix3< T > Divide (const Matrix3< T > &p_left, const U p_scalar)
Divide matrix p_left by scalar.
static constexpr bool AreEqual (const Matrix3< T > &p_left, const Matrix3< T > &p_right)
Return true if the two matrices are identical.
static constexpr bool IsIdentity (const Matrix3< T > &p_other)
Return true if the two matrices are identical.
static constexpr std::string ToString (const Matrix3< T > &p_matrix)
Function used to debug values from the matrix.
static T Determinant (const Matrix3< T > &p_matrix3)
Calculates the determinant of the matrix.
static constexpr Matrix3< T > Transpose (const Matrix3< T > &p_matrix3)
Returns this matrix transposed.
static constexpr Matrix3< T > Normalize (const Matrix3< T > &p_matrix)
Returns this matrix with a magnitude of 1.
template<typename U >
static constexpr Matrix3< T > CreateTranslation (const Vector2< U > &p_vector)
Creates a translation identity matrix with a Vector2 offset.
static constexpr Matrix3< T > CreateRotation (const float p_angle)
Creates a rotation identity matrix with an angle in degrees.
template<typename U >
static constexpr Matrix3< T > CreateScaling (const Vector2< U > &p_vector)
Creates a scaling identity matrix with a Vector2.
template<typename U >
static constexpr Matrix3< T > CreateTransformation (const Vector2< U > &p_pos, const float p_angle, const Vector2< U > &p_scale)
Creates a translation, rotation and scaling matrix.
template<typename U >
static constexpr Matrix3< T > Add (const Matrix3< T > &p_left, const Matrix3< U > &p_right)
Add left matrix to the right matrix.
template<typename U >
static constexpr Matrix3< T > Subtract (const Matrix3< T > &p_left, const Matrix3< U > &p_right)
Subtract left matrix to the right matrix.
template<typename U >
static constexpr Matrix3< T > Multiply (const Matrix3< T > &p_left, U p_scalar)
Multiply scalar to matrix left.
template<typename U >
static constexpr Matrix3< T > Multiply (const Matrix3< T > &p_left, const Matrix3< U > &p_right)
Multiply scalar to matrix left.
template<typename U >
static constexpr Matrix3< T > Divide (const Matrix3< T > &p_left, const U p_scalar)
Divide matrix p_left by scalar.
static constexpr bool AreEqual (const Matrix3< T > &p_left, const Matrix3< T > &p_right)
Return true if the two matrices are identical.
static constexpr bool IsIdentity (const Matrix3< T > &p_other)
Return true if the two matrices are identical.
static constexpr std::string ToString (const Matrix3< T > &p_matrix)
Function used to debug values from the matrix.
Data Fields
T m_data [9]
Static Public Attributes
static Matrix3< T > identity
This is a const matrix that has 1 in the diagonal and 0 elsewhere.
static Matrix3< T > zero
This is a const matrix that has 0 everywhere.
Detailed Description
template<typename T>
struct GPM::Matrix3< T >
A standard 3 by 3 Matrix. Default value is an identity matrix
Definition at line 11 of file Matrix3.h.
Constructor & Destructor Documentation
Matrix3() [1/12]
template<typename T > constexpr Matrix3::Matrix3 ()
Default Constructor.
Definition at line 23 of file Matrix3.inl.
 {
     memcpy(m_data, identity.m_data, 9 * sizeof(T));
 }
~Matrix3() [1/2]
template<typename T> GPM::Matrix3< T >::~Matrix3 () default
Default Destructor.
Matrix3() [2/12]
template<typename T > constexpr Matrix3::Matrix3 (const T p_i0, const T p_i1, const T p_i2, const T p_i3, const T p_i4, const T p_i5, const T p_i6, const T p_i7, const T p_i8)
Constructor with parameters.
Parameters
p_i0 1st element
p_i1 2nd element
p_i2 3rd element
p_i3 4th element
p_i4 5th element
p_i5 6th element
p_i6 7th element
p_i7 8th element
p_i8 9th element
Definition at line 29 of file Matrix3.inl.
                               : m_data{ p_i0, p_i1, p_i2,
                                         p_i3, p_i4, p_i5,
                                         p_i6, p_i7, p_i8 } {}
Matrix3() [3/12]
template<typename T > constexpr Matrix3::Matrix3 (const T p_data[9])
Constructor from already created array.
Parameters
p_data : Array with a size of 9 elements
Definition at line 37 of file Matrix3.inl.
 {
     memcpy(m_data, p_data, 9 * sizeof(T));
 }
Matrix3() [4/12]
template<typename T > constexpr Matrix3::Matrix3 (const Matrix3< T > & p_other)
Copy Constructor.
Parameters
p_other : Matrix to construct from
Definition at line 43 of file Matrix3.inl.
 {
     memcpy(m_data, p_other.m_data, 9 * sizeof(T));
 }
References GPM::Matrix3< T >::m_data.
Matrix3() [5/12]
template<typename T > template<typename U > constexpr Matrix3::Matrix3 (const Matrix3< U > & p_other)
Template Copy Constructor.
Parameters
p_other : Matrix to construct from
Definition at line 50 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] = p_other.m_data[i];
 }
References GPM::Matrix3< T >::m_data.
Matrix3() [6/12]
template<typename T > constexpr Matrix3::Matrix3 (Matrix3< T > && p_other) noexcept
Move Constructor.
Parameters
p_other : Matrix to construct from
Definition at line 57 of file Matrix3.inl.
 {
     memcpy(m_data, p_other.m_data, 9 * sizeof(T));
 }
Matrix3() [7/12]
template<typename T> constexpr GPM::Matrix3< T >::Matrix3 ()
Default Constructor.
~Matrix3() [2/2]
template<typename T> GPM::Matrix3< T >::~Matrix3 () default
Default Destructor.
Matrix3() [8/12]
template<typename T> constexpr GPM::Matrix3< T >::Matrix3 (const T p_i0, const T p_i1, const T p_i2, const T p_i3, const T p_i4, const T p_i5, const T p_i6, const T p_i7, const T p_i8)
Constructor with parameters.
Parameters
p_i0 1st element
p_i1 2nd element
p_i2 3rd element
p_i3 4th element
p_i4 5th element
p_i5 6th element
p_i6 7th element
p_i7 8th element
p_i8 9th element
Matrix3() [9/12]
template<typename T> constexpr GPM::Matrix3< T >::Matrix3 (const T p_data[9])
Constructor from already created array.
Parameters
p_data : Array with a size of 9 elements
Matrix3() [10/12]
template<typename T> constexpr GPM::Matrix3< T >::Matrix3 (const Matrix3< T > & p_other)
Copy Constructor.
Parameters
p_other : Matrix to construct from
Matrix3() [11/12]
template<typename T> template<typename U > constexpr GPM::Matrix3< T >::Matrix3 (const Matrix3< U > & p_other)
Template Copy Constructor.
Parameters
p_other : Matrix to construct from
Matrix3() [12/12]
template<typename T> constexpr GPM::Matrix3< T >::Matrix3 (Matrix3< T > && p_other) noexcept
Move Constructor.
Parameters
p_other : Matrix to construct from
Member Function Documentation
Add() [1/4]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::Add (const Matrix3< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
Add() [2/4]
template<typename T > template<typename U > Matrix3< T > & Matrix3::Add (const Matrix3< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
Definition at line 296 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] += p_other.m_data[i];
     return { *this };
 }
References GPM::Matrix3< T >::m_data.
Referenced by GPM::Matrix3< T >::Add().
Add() [3/4]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::Add (const Matrix3< T > & p_left, const Matrix3< U > & p_right) static
Add left matrix to the right matrix.
Parameters
p_left : The first matrix you want to add
p_right : The second matrix to be added to the first one
Returns
The copy of the Matrix operation result
Add() [4/4]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::Add (const Matrix3< T > & p_left, const Matrix3< U > & p_right) static
Add left matrix to the right matrix.
Parameters
p_left : The first matrix you want to add
p_right : The second matrix to be added to the first one
Returns
The copy of the Matrix operation result
Definition at line 306 of file Matrix3.inl.
 {
     return Matrix3<T>(p_left).Add(p_right);
 }
References GPM::Matrix3< T >::Add().
AreEqual() [1/2]
template<typename T> static constexpr bool GPM::Matrix3< T >::AreEqual (const Matrix3< T > & p_left, const Matrix3< T > & p_right) static
Return true if the two matrices are identical.
Parameters
p_left The left matrix
p_right The right matrix
Returns
True or false
AreEqual() [2/2]
template<typename T > constexpr bool Matrix3::AreEqual (const Matrix3< T > & p_left, const Matrix3< T > & p_right) static
Return true if the two matrices are identical.
Parameters
p_left The left matrix
p_right The right matrix
Returns
True or false
Definition at line 513 of file Matrix3.inl.
 {
     return p_left.Equals(p_right);
 }
References GPM::Matrix3< T >::Equals().
CreateRotation() [1/2]
template<typename T> static constexpr Matrix3<T> GPM::Matrix3< T >::CreateRotation (const float p_angle) static
Creates a rotation identity matrix with an angle in degrees.
Parameters
p_angle : The desired angle in degrees to rotate the matrix
Returns
The rotated identity matrix
CreateRotation() [2/2]
template<typename T > constexpr Matrix3< T > Matrix3::CreateRotation (const float p_angle) static
Creates a rotation identity matrix with an angle in degrees.
Parameters
p_angle : The desired angle in degrees to rotate the matrix
Returns
The rotated identity matrix
Definition at line 246 of file Matrix3.inl.
 {
     Matrix3<T> tempMat = identity;
     tempMat.m_data[0] = Tools::Utils::Cos(p_angle);
     tempMat.m_data[1] = Tools::Utils::Sin(p_angle);
     tempMat.m_data[3] = -Tools::Utils::Sin(p_angle);
     tempMat.m_data[4] = Tools::Utils::Cos(p_angle);
     return tempMat;
 }
References GPM::Tools::Utils::Cos(), GPM::Matrix3< T >::m_data, and GPM::Tools::Utils::Sin().
CreateScaling() [1/2]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::CreateScaling (const Vector2< U > & p_vector) static
Creates a scaling identity matrix with a Vector2.
Parameters
p_vector : the desired 2D scale
Returns
The scaled identity matrix
CreateScaling() [2/2]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::CreateScaling (const Vector2< U > & p_vector) static
Creates a scaling identity matrix with a Vector2.
Parameters
p_vector : the desired 2D scale
Returns
The scaled identity matrix
Definition at line 267 of file Matrix3.inl.
 {
     Matrix3<T> tempMat = identity;
     tempMat.m_data[0] = p_vector.x;
     tempMat.m_data[4] = p_vector.y;
     return tempMat;
 }
References GPM::Matrix3< T >::m_data, GPM::Vector2< T >::x, and GPM::Vector2< T >::y.
CreateTransformation() [1/2]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::CreateTransformation (const Vector2< U > & p_pos, const float p_angle, const Vector2< U > & p_scale) static
Creates a translation, rotation and scaling matrix.
Parameters
p_pos : The position to set the matrix to
p_angle : The rotation to orient the matrix to
p_scale : The scale to set the matrix to
Returns
A translation matrix set with the given parameters
CreateTransformation() [2/2]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::CreateTransformation (const Vector2< U > & p_pos, const float p_angle, const Vector2< U > & p_scale) static
Creates a translation, rotation and scaling matrix.
Parameters
p_pos : The position to set the matrix to
p_angle : The rotation to orient the matrix to
p_scale : The scale to set the matrix to
Returns
A translation matrix set with the given parameters
Definition at line 277 of file Matrix3.inl.
 {
     static_assert(!std::is_integral<T>::value, "Matrix3::CreateTransformation : Can't do Transform Matrices with Matrix3<int>, as values would be rounded to 0");
     Matrix3<T> tempMat = identity;
     Matrix3<T> t = CreateTranslation(p_pos);
     Matrix3<T> r = CreateRotation(p_angle);
     Matrix3<T> s = CreateScaling(p_scale);
     tempMat = t * r * s;
     return tempMat;
 }
CreateTranslation() [1/2]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::CreateTranslation (const Vector2< U > & p_vector) static
Creates a translation identity matrix with a Vector2 offset.
Parameters
p_vector : The desired 2D off-set
Returns
The translated identity matrix
CreateTranslation() [2/2]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::CreateTranslation (const Vector2< U > & p_vector) static
Creates a translation identity matrix with a Vector2 offset.
Parameters
p_vector : The desired 2D off-set
Returns
The translated identity matrix
Definition at line 228 of file Matrix3.inl.
 {
     Matrix3<T> tempMat = identity;
     tempMat.m_data[2] = p_vector.x;
     tempMat.m_data[5] = p_vector.y;
     return tempMat;
 }
References GPM::Matrix3< T >::m_data, GPM::Vector2< T >::x, and GPM::Vector2< T >::y.
Determinant() [1/4]
template<typename T > T Matrix3::Determinant ()
Calculates the determinant of the matrix.
Returns
The determinant in any arithmetic type you want
Definition at line 105 of file Matrix3.inl.
 {
     return ((m_data[0] * ((m_data[4] * m_data[8]) - (m_data[5] * m_data[7])))
         - (m_data[1] * ((m_data[3] * m_data[8]) - (m_data[5] * m_data[6])))
         + (m_data[2] * ((m_data[3] * m_data[7]) - (m_data[4] * m_data[6]))));
 }
Determinant() [2/4]
template<typename T> T GPM::Matrix3< T >::Determinant ()
Calculates the determinant of the matrix.
Returns
The determinant in any arithmetic type you want
Determinant() [3/4]
template<typename T > T Matrix3::Determinant (const Matrix3< T > & p_matrix3) static
Calculates the determinant of the matrix.
Parameters
p_matrix3 : The matrix to get the Determinant from
Returns
The determinant in any arithmetic type you want
Definition at line 113 of file Matrix3.inl.
 {
     return ((p_matrix3.m_data[0] * ((p_matrix3.m_data[4] * p_matrix3.m_data[8]) - (p_matrix3.m_data[5] * p_matrix3.m_data[7])))
           - (p_matrix3.m_data[1] * ((p_matrix3.m_data[3] * p_matrix3.m_data[8]) - (p_matrix3.m_data[5] * p_matrix3.m_data[6])))
           + (p_matrix3.m_data[2] * ((p_matrix3.m_data[3] * p_matrix3.m_data[7]) - (p_matrix3.m_data[4] * p_matrix3.m_data[6]))));
 }
References GPM::Matrix3< T >::m_data.
Determinant() [4/4]
template<typename T> static T GPM::Matrix3< T >::Determinant (const Matrix3< T > & p_matrix3) static
Calculates the determinant of the matrix.
Parameters
p_matrix3 : The matrix to get the Determinant from
Returns
The determinant in any arithmetic type you want
Divide() [1/4]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::Divide (U p_scalar)
Divide elements by scalar.
Parameters
p_scalar : The value you want to scale the matrix with
Returns
The current Matrix modified
Divide() [2/4]
template<typename T > template<typename U > Matrix3< T > & Matrix3::Divide (U p_scalar)
Divide elements by scalar.
Parameters
p_scalar : The value you want to scale the matrix with
Returns
The current Matrix modified
Definition at line 440 of file Matrix3.inl.
 {
     for (auto& val : m_data)
         val /= p_scalar;
     return { *this };
 }
Referenced by GPM::Matrix3< T >::Divide(), and GPM::Matrix3< T >::operator/().
Divide() [3/4]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::Divide (const Matrix3< T > & p_left, const U p_scalar) static
Divide matrix p_left by scalar.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this scalar to the other parameter
Returns
The copy of the Matrix operation result
Divide() [4/4]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::Divide (const Matrix3< T > & p_left, const U p_scalar) static
Divide matrix p_left by scalar.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this scalar to the other parameter
Returns
The copy of the Matrix operation result
Definition at line 450 of file Matrix3.inl.
 {
      return p_left.Divide(p_scalar);
 }
References GPM::Matrix3< T >::Divide().
Equals() [1/2]
template<typename T> constexpr bool GPM::Matrix3< T >::Equals (const Matrix3< T > & p_other) const
Return true if the two matrices are identical.
Parameters
p_other The matrix used for the checkup
Returns
True or false
Equals() [2/2]
template<typename T > constexpr bool Matrix3::Equals (const Matrix3< T > & p_other) const
Return true if the two matrices are identical.
Parameters
p_other The matrix used for the checkup
Returns
True or false
Definition at line 502 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; i++)
     {
         if (m_data[i] != p_other.m_data[i])
             return false;
     }
     return true;
 }
References GPM::Matrix3< T >::m_data.
Referenced by GPM::Matrix3< T >::AreEqual(), and GPM::Matrix3< T >::IsIdentity().
GetColumn() [1/2]
template<typename T > constexpr Vector3< T > Matrix3::GetColumn (const int p_column)
Attempts to retrieve a column from the matrix.
Parameters
p_column : Which column to retrieve
Returns
The column in a Vector type
Definition at line 153 of file Matrix3.inl.
 {
     if (p_column < 0 || p_column > 3)
         throw std::logic_error("Matrix3::GetColumn() p_column is inferior to 0 or superior to 3. There are no columns at those indexes");
     return { m_data[p_column], m_data[p_column + 3], m_data[p_column + 6] };
 }
GetColumn() [2/2]
template<typename T> constexpr Vector3<T> GPM::Matrix3< T >::GetColumn (const int p_column)
Attempts to retrieve a column from the matrix.
Parameters
p_column : Which column to retrieve
Returns
The column in a Vector type
GetRow() [1/2]
template<typename T > constexpr Vector3< T > Matrix3::GetRow (const int p_row)
Attempts to retrieve a row from the matrix.
Parameters
p_row : Which row to retrieve
Returns
The row in a Vector type
Definition at line 176 of file Matrix3.inl.
 {
     if (p_row < 0 || p_row > 3)
         throw std::logic_error("Matrix3::GetRow() p_row is inferior to 0 or superior to 3. There are no rows at those indexes");
     return { m_data[4 * p_row], m_data[(4 * p_row) + 1], m_data[(4 * p_row) + 2] };
 }
GetRow() [2/2]
template<typename T> constexpr Vector3<T> GPM::Matrix3< T >::GetRow (const int p_row)
Attempts to retrieve a row from the matrix.
Parameters
p_row : Which row to retrieve
Returns
The row in a Vector type
IsIdentity() [1/2]
template<typename T> static constexpr bool GPM::Matrix3< T >::IsIdentity (const Matrix3< T > & p_other) static
Return true if the two matrices are identical.
Parameters
p_other The matrix used for the checkup
Returns
True or false
IsIdentity() [2/2]
template<typename T > constexpr bool Matrix3::IsIdentity (const Matrix3< T > & p_other) static
Return true if the two matrices are identical.
Parameters
p_other The matrix used for the checkup
Returns
True or false
Definition at line 519 of file Matrix3.inl.
 {
     return p_other.Equals(identity);
 }
References GPM::Matrix3< T >::Equals().
LookAt() [1/2]
template<typename T> template<typename U > constexpr Matrix3<T>& GPM::Matrix3< T >::LookAt (const Vector3< U > & p_dir, const Vector3< U > & p_up, Matrix3< T > & p_matrix)
Computes a transformation matrix that looks at a target.
/!\ W.I.P. NOT FUNCTIONAL AS OF NOW /!\
Parameters
LookAt() [2/2]
template<typename T> template<typename U > constexpr Matrix3<T>& GPM::Matrix3< T >::LookAt (const Vector3< U > & p_dir, const Vector3< U > & p_up, Matrix3< T > & p_matrix)
Computes a transformation matrix that looks at a target.
Parameters
Multiply() [1/8]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::Multiply (U p_scalar)
Multiply scalar to elements.
Parameters
p_scalar : The value you want to scale the matrix with
Returns
The current Matrix modified
Multiply() [2/8]
template<typename T > template<typename U > Matrix3< T > & Matrix3::Multiply (U p_scalar)
Multiply scalar to elements.
Parameters
p_scalar : The value you want to scale the matrix with
Returns
The current Matrix modified
Definition at line 366 of file Matrix3.inl.
 {
     for (auto& val : m_data)
         val *= p_scalar;
     return { *this };
 }
Referenced by GPM::Matrix3< T >::Multiply(), and GPM::Matrix3< T >::operator *().
Multiply() [3/8]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::Multiply (const Matrix3< U > & p_other)
Multiply matrix with another matrix.
Parameters
p_other : The matrix you want to use as a scalar
Returns
The current Matrix modified
Multiply() [4/8]
template<typename T > template<typename U > Matrix3< T > & Matrix3::Multiply (const Matrix3< U > & p_other)
Multiply matrix with another matrix.
Parameters
p_other : The matrix you want to use as a scalar
Returns
The current Matrix modified
Definition at line 376 of file Matrix3.inl.
 {
     Matrix3<T> tmpMat(this->m_data);
     for (unsigned int i = 0; i < 9; i += 3)
     {
         for (unsigned int j = 0; j < 3; j++)
         {
             m_data[i + j] = (tmpMat.m_data[i] * p_other.m_data[j])
                       + (tmpMat.m_data[i + 1] * p_other.m_data[j + 3])
                       + (tmpMat.m_data[i + 2] * p_other.m_data[j + 6]);
         }
     }
     return { *this };
 }
References GPM::Matrix3< T >::m_data.
Multiply() [5/8]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::Multiply (const Matrix3< T > & p_left, U p_scalar) static
Multiply scalar to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this scalar to the other parameter
Returns
The copy of the Matrix operation result
Multiply() [6/8]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::Multiply (const Matrix3< T > & p_left, U p_scalar) static
Multiply scalar to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_scalar : Multiply this scalar to the other parameter
Returns
The copy of the Matrix operation result
Definition at line 394 of file Matrix3.inl.
 {
     return Matrix3<T>(p_left).Multiply(p_scalar);
 }
References GPM::Matrix3< T >::Multiply().
Multiply() [7/8]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::Multiply (const Matrix3< T > & p_left, const Matrix3< U > & p_right) static
Multiply scalar to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_right : Multiply this matrix to the other parameter
Returns
The copy of the Matrix operation result
Multiply() [8/8]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::Multiply (const Matrix3< T > & p_left, const Matrix3< U > & p_right) static
Multiply scalar to matrix left.
Parameters
p_left : Multiply this matrix by the other parameter
p_right : Multiply this matrix to the other parameter
Returns
The copy of the Matrix operation result
Definition at line 401 of file Matrix3.inl.
 {
     return Matrix3<T>(p_left).Multiply(p_right);
 }
References GPM::Matrix3< T >::Multiply().
Normalize() [1/4]
template<typename T > constexpr Matrix3< T > & Matrix3::Normalize ()
Returns this matrix with a magnitude of 1.
Returns
The modified matrix with a magnitude of 1
Definition at line 197 of file Matrix3.inl.
 {
     T determinant = Determinant();
     if (determinant == 0)
         throw std::logic_error("Matrix3::Normalize() : Cannot divide by 0. Determinant was 0");
     for (auto& i : m_data)
     {
         i /= determinant;
     }
     return {*this};
 }
Referenced by GPM::Matrix3< T >::Normalize().
Normalize() [2/4]
template<typename T> constexpr Matrix3<T>& GPM::Matrix3< T >::Normalize ()
Returns this matrix with a magnitude of 1.
Returns
The modified matrix with a magnitude of 1
Normalize() [3/4]
template<typename T > constexpr Matrix3< T > Matrix3::Normalize (const Matrix3< T > & p_matrix) static
Returns this matrix with a magnitude of 1.
Returns
The modified matrix with a magnitude of 1
Definition at line 212 of file Matrix3.inl.
 {
     return p_matrix.Normalize();
 }
References GPM::Matrix3< T >::Normalize().
Normalize() [4/4]
template<typename T> static constexpr Matrix3<T> GPM::Matrix3< T >::Normalize (const Matrix3< T > & p_matrix) static
Returns this matrix with a magnitude of 1.
Returns
The modified matrix with a magnitude of 1
operator *() [1/4]
template<typename T> template<class U > constexpr Matrix3<T> GPM::Matrix3< T >::operator * (const Matrix3< U > & p_other) const
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The copy of the Matrix operation result
operator *() [2/4]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::operator * (const Matrix3< U > & p_other) const
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The copy of the Matrix operation result
Definition at line 408 of file Matrix3.inl.
 {
     return Matrix3<T>(*this).Multiply(p_other);
 }
References GPM::Matrix3< T >::Multiply().
operator *() [3/4]
template<typename T> template<class U > constexpr Matrix3<T> GPM::Matrix3< T >::operator * (const U p_scalar) const
Multiply matrix to the current matrix.
Parameters
p_scalar : Multiply this matrix to the scalar
Returns
The copy of the Matrix operation result
operator *() [4/4]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::operator * (const U p_scalar) const
Multiply matrix to the current matrix.
Parameters
p_scalar : Multiply this matrix to the scalar
Returns
The copy of the Matrix operation result
Definition at line 415 of file Matrix3.inl.
 {
     return Matrix3<T>(*this).Multiply(p_scalar);
 }
References GPM::Matrix3< T >::Multiply().
operator *=() [1/4]
template<typename T> template<class U > Matrix3<T>& GPM::Matrix3< T >::operator *= (const U p_scalar)
Multiply matrix to the current matrix.
Parameters
p_scalar : Multiply this matrix to the scalar
Returns
The current Matrix modified
operator *=() [2/4]
template<typename T > template<typename U > Matrix3< T > & Matrix3::operator *= (const U p_scalar)
Multiply matrix to the current matrix.
Parameters
p_scalar : Multiply this matrix to the scalar
Returns
The current Matrix modified
Definition at line 422 of file Matrix3.inl.
 {
     return  { Multiply(p_scalar) };
 }
operator *=() [3/4]
template<typename T> template<class U > Matrix3<T>& GPM::Matrix3< T >::operator *= (const Matrix3< U > & p_other)
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The current Matrix modified
operator *=() [4/4]
template<typename T > template<typename U > Matrix3< T > & Matrix3::operator *= (const Matrix3< U > & p_other)
Multiply matrix to the current matrix.
Parameters
p_other : Multiply this matrix to the current one
Returns
The current Matrix modified
Definition at line 429 of file Matrix3.inl.
 {
     return  { Multiply(p_other) };
 }
operator -=() [1/2]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::operator -= (const Matrix3< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
operator -=() [2/2]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::operator -= (const Matrix3< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
operator!=() [1/2]
template<typename T> constexpr bool GPM::Matrix3< T >::operator!= (const Matrix3< T > & p_other) const
Return true if the two matrices are different.
Parameters
p_other The matrix used for the checkup
Returns
True or false
operator!=() [2/2]
template<typename T > constexpr bool Matrix3::operator!= (const Matrix3< T > & p_other) const
Return true if the two matrices are different.
Parameters
p_other The matrix used for the checkup
Returns
True or false
Definition at line 531 of file Matrix3.inl.
 {
     return !Equals(p_other);
 }
operator+() [1/2]
template<typename T> template<typename U > constexpr Matrix3<T> GPM::Matrix3< T >::operator+ (const Matrix3< U > & p_other) const
Return the summation of other matrix and current matrix.
Parameters
p_other : The other matrix you want to add
Returns
The copy of the Matrix operation result
operator+() [2/2]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::operator+ (const Matrix3< U > & p_other) const
Return the summation of other matrix and current matrix.
Parameters
p_other : The other matrix you want to add
Returns
The copy of the Matrix operation result
Definition at line 313 of file Matrix3.inl.
 {
     return Add(this, p_other);
 }
operator+=() [1/2]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::operator+= (const Matrix3< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
operator+=() [2/2]
template<typename T > template<typename U > Matrix3< T > & Matrix3::operator+= (const Matrix3< U > & p_other)
Add other matrix to the current matrix.
Parameters
p_other : The other matrix you want to add to the current one
Returns
The current Matrix modified
Definition at line 320 of file Matrix3.inl.
 {
     return Add(p_other);
 }
operator-() [1/2]
template<typename T> template<typename U > constexpr Matrix3<T> GPM::Matrix3< T >::operator- (const Matrix3< U > & p_other) const
Return the subtraction of other matrix and current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The copy of the Matrix operation result
operator-() [2/2]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::operator- (const Matrix3< U > & p_other) const
Return the subtraction of other matrix and current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The copy of the Matrix operation result
Definition at line 348 of file Matrix3.inl.
 {
     return Subtract(this, p_other);
 }
operator/() [1/2]
template<typename T> template<class U > constexpr Matrix3<T> GPM::Matrix3< T >::operator/ (const U p_scalar) const
Divide matrix p_left by scalar.
Parameters
p_scalar : the scalar to divide
Returns
The copy of the Matrix operation result
operator/() [2/2]
template<typename T > template<class U > constexpr Matrix3< T > Matrix3::operator/ (const U p_scalar) const
Divide matrix p_left by scalar.
Parameters
p_scalar : the scalar to divide
Returns
The copy of the Matrix operation result
Definition at line 457 of file Matrix3.inl.
 {
      return Matrix3<T>(*this).Divide(p_scalar);
 }
References GPM::Matrix3< T >::Divide().
operator/=() [1/2]
template<typename T> template<class U > Matrix3<T>& GPM::Matrix3< T >::operator/= (const U p_scalar)
Divide elements by scalar.
Parameters
p_scalar : The value you want to divide the matrix by
Returns
The current Matrix modified
operator/=() [2/2]
template<typename T > template<class U > Matrix3< T > & Matrix3::operator/= (const U p_scalar)
Divide elements by scalar.
Parameters
p_scalar : The value you want to divide the matrix by
Returns
The current Matrix modified
Definition at line 464 of file Matrix3.inl.
 {
      return { Divide(p_scalar) };
 }
operator=() [1/8]
template<typename T > constexpr Matrix3< T > & Matrix3::operator= (const Matrix3< T > & p_other)
Assignment operator for Matrix3.
Parameters
p_other The matrix to construct from
Definition at line 63 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] = p_other.m_data[i];
     return *this;
 }
References GPM::Matrix3< T >::m_data.
operator=() [2/8]
template<typename T> constexpr Matrix3<T>& GPM::Matrix3< T >::operator= (const Matrix3< T > & p_other)
Assignment operator for Matrix3.
Parameters
p_other The matrix to construct from
operator=() [3/8]
template<typename T > template<typename U > constexpr Matrix3< T > & Matrix3::operator= (const Matrix3< U > & p_other)
Assignment operator for Matrix3.
Parameters
p_other The matrix to construct from
Definition at line 73 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] = static_cast<const T>(p_other.m_data[i]);
     return *this;
 }
References GPM::Matrix3< T >::m_data.
operator=() [4/8]
template<typename T> template<typename U > constexpr Matrix3<T>& GPM::Matrix3< T >::operator= (const Matrix3< U > & p_other)
Assignment operator for Matrix3.
Parameters
p_other The matrix to construct from
operator=() [5/8]
template<typename T> constexpr Matrix3<T>& GPM::Matrix3< T >::operator= (Matrix3< T > && p_other) noexcept
Assignment move operator for Matrix3.
Parameters
p_other The matrix to construct from
operator=() [6/8]
template<typename T > constexpr Matrix3< T > & Matrix3::operator= (Matrix3< T > && p_other) noexcept
Assignment move operator for Matrix3.
Parameters
p_other The matrix to construct from
Definition at line 81 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] = p_other.m_data[i];
     return *this;
 }
operator=() [7/8]
template<typename T> template<typename U > constexpr Matrix3<T>& GPM::Matrix3< T >::operator= (Matrix3< U > && p_other) noexcept
Assignment move operator for Matrix3.
Parameters
p_other The matrix to construct from
operator=() [8/8]
template<typename T > template<typename U > constexpr Matrix3< T > & Matrix3::operator= (Matrix3< U > && p_other) noexcept
Assignment move operator for Matrix3.
Parameters
p_other The matrix to construct from
Definition at line 91 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] = p_other.m_data[i];
     return *this;
 }
operator==() [1/2]
template<typename T> constexpr bool GPM::Matrix3< T >::operator== (const Matrix3< T > & p_other) const
Return true if the two matrices are identical.
Parameters
p_other The matrix used for the checkup
Returns
True or false
operator==() [2/2]
template<typename T > constexpr bool Matrix3::operator== (const Matrix3< T > & p_other) const
Return true if the two matrices are identical.
Parameters
p_other The matrix used for the checkup
Returns
True or false
Definition at line 525 of file Matrix3.inl.
 {
     return Equals(p_other);
 }
Rotate() [1/2]
template<typename T > constexpr Matrix3< T > & Matrix3::Rotate (const float p_angle)
Rotate the current matrix with an angle in degrees.
Parameters
p_angle : The desired angle in degrees to rotate the matrix
Returns
The current matrix rotated
Definition at line 236 of file Matrix3.inl.
 {
     m_data[0] = Tools::Utils::CosF(p_angle);
     m_data[1] = Tools::Utils::SinF(p_angle);
     m_data[3] = -Tools::Utils::SinF(p_angle);
     m_data[4] = Tools::Utils::CosF(p_angle);
     return { *this };
 }
References GPM::Tools::Utils::CosF(), and GPM::Tools::Utils::SinF().
Rotate() [2/2]
template<typename T> constexpr Matrix3<T>& GPM::Matrix3< T >::Rotate (const float p_angle)
Rotate the current matrix with an angle in degrees.
Parameters
p_angle : The desired angle in degrees to rotate the matrix
Returns
The current matrix rotated
Scale() [1/2]
template<typename T > template<typename U > constexpr Matrix3< T > & Matrix3::Scale (const Vector2< U > & p_vector)
Scale the current matrix with a Vector2.
Parameters
p_vector : The desired 2D Scale
Returns
The current matrix scaled
Definition at line 258 of file Matrix3.inl.
 {
     m_data[0] = p_vector.x;
     m_data[4] = p_vector.y;
     return { *this };
 }
References GPM::Vector2< T >::x, and GPM::Vector2< T >::y.
Scale() [2/2]
template<typename T> template<typename U > constexpr Matrix3<T>& GPM::Matrix3< T >::Scale (const Vector2< U > & p_vector)
Scale the current matrix with a Vector2.
Parameters
p_vector : The desired 2D Scale
Returns
The current matrix scaled
SetColumn() [1/2]
template<typename T > template<typename U > constexpr void Matrix3::SetColumn (const int p_column, const Vector3< U > & p_vector)
Attempts to set a column in the matrix.
Parameters
p_column : Which column to retrieve
p_vector : The values to set in the column
Definition at line 164 of file Matrix3.inl.
 {
     if (p_column < 0 || p_column > 3)
         throw std::logic_error("Matrix3::SetColumn() p_column is inferior to 0 or superior to 3. There are no columns at those indexes");
     m_data[p_column] = p_vector.x;
     m_data[p_column + 3] = p_vector.y;
     m_data[p_column + 6] = p_vector.z;
 }
References GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
SetColumn() [2/2]
template<typename T> template<typename U > constexpr void GPM::Matrix3< T >::SetColumn (const int p_column, const Vector3< U > & p_vector)
Attempts to set a column in the matrix.
Parameters
p_column : Which column to retrieve
p_vector : The values to set in the column
SetRow() [1/2]
template<typename T> template<typename U > constexpr void GPM::Matrix3< T >::SetRow (const int p_row, const Vector3< U > & p_vector)
Attempts to set a row in the matrix.
Parameters
p_row : Which row to retrieve
p_vector : The values to set in the row
SetRow() [2/2]
template<typename T > template<typename U > constexpr void Matrix3::SetRow (const int p_row, const Vector3< U > & p_vector)
Attempts to set a row in the matrix.
Parameters
p_row : Which row to retrieve
p_vector : The values to set in the row
Definition at line 186 of file Matrix3.inl.
 {
     if (p_row < 0 || p_row > 3)
         throw std::logic_error("Matrix3::SetRow() p_row is inferior to 0 or superior to 3. There are no rows at those indexes");
     m_data[p_row] = p_vector.x;
     m_data[p_row + 1] = p_vector.y;
     m_data[p_row + 2] = p_vector.z;
 }
References GPM::Vector3< T >::x, GPM::Vector3< T >::y, and GPM::Vector3< T >::z.
Subtract() [1/4]
template<typename T> template<typename U > Matrix3<T>& GPM::Matrix3< T >::Subtract (const Matrix3< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
Subtract() [2/4]
template<typename T > template<typename U > Matrix3< T > & Matrix3::Subtract (const Matrix3< U > & p_other)
Subtract other matrix to the current matrix.
Parameters
p_other : The matrix you want to subtract to the current one
Returns
The current Matrix modified
Definition at line 331 of file Matrix3.inl.
 {
     for (unsigned int i = 0; i < 9; ++i)
         m_data[i] -= static_cast<const T>(p_other.m_data[i]);
     return { *this };
 }
References GPM::Matrix3< T >::m_data.
Referenced by GPM::Matrix3< T >::Subtract().
Subtract() [3/4]
template<typename T> template<typename U > static constexpr Matrix3<T> GPM::Matrix3< T >::Subtract (const Matrix3< T > & p_left, const Matrix3< U > & p_right) static
Subtract left matrix to the right matrix.
Parameters
p_left : The first matrix you want to subtract to
p_right : The second matrix to be subtracted from the first one
Returns
The copy of the Matrix operation result
Subtract() [4/4]
template<typename T > template<typename U > constexpr Matrix3< T > Matrix3::Subtract (const Matrix3< T > & p_left, const Matrix3< U > & p_right) static
Subtract left matrix to the right matrix.
Parameters
p_left : The first matrix you want to subtract to
p_right : The second matrix to be subtracted from the first one
Returns
The copy of the Matrix operation result
Definition at line 341 of file Matrix3.inl.
 {
     return Matrix3<T>(p_left).Subtract(p_right);
 }
References GPM::Matrix3< T >::Subtract().
ToString() [1/4]
template<typename T> constexpr std::string GPM::Matrix3< T >::ToString ()
function used to debug values from the matrix
ToString() [2/4]
template<typename T > constexpr std::string Matrix3::ToString ()
function used to debug values from the matrix
Definition at line 477 of file Matrix3.inl.
 {
     std::stringstream stringStream;
     stringStream << '[' << m_data[0] << "  " << m_data[1] << "  " << m_data[2] << "]\n"
         << '|' << m_data[3] << "  " << m_data[4] << "  " << m_data[5] << "|\n"
         << '[' << m_data[6] << "  " << m_data[7] << "  " << m_data[8] << "]\n";
     return { stringStream.str() };
 }
ToString() [3/4]
template<typename T> static constexpr std::string GPM::Matrix3< T >::ToString (const Matrix3< T > & p_matrix) static
Function used to debug values from the matrix.
Parameters
p_matrix The matrix to print
ToString() [4/4]
template<typename T > constexpr std::string Matrix3::ToString (const Matrix3< T > & p_matrix) static
Function used to debug values from the matrix.
Parameters
p_matrix The matrix to print
Definition at line 487 of file Matrix3.inl.
 {
     std::stringstream stringStream;
     stringStream << '[' << p_matrix.m_data[0] << "  " << p_matrix.m_data[1] << "  " << p_matrix.m_data[2] << "]\n"
         << '|' << p_matrix.m_data[3] << "  " << p_matrix.m_data[4] << "  " << p_matrix.m_data[5] << "|\n"
         << '[' << p_matrix.m_data[6] << "  " << p_matrix.m_data[7] << "  " << p_matrix.m_data[8] << "]\n";
     return { stringStream.str() };
 }
References GPM::Matrix3< T >::m_data.
Translate() [1/2]
template<typename T> template<typename U > constexpr Matrix3<T>& GPM::Matrix3< T >::Translate (const Vector2< U > & p_vector)
Translates the current matrix with a Vector2.
Parameters
p_vector : The desired 2D off-set
Returns
The current matrix translated
Translate() [2/2]
template<typename T > template<typename U > constexpr Matrix3< T > & Matrix3::Translate (const Vector2< U > & p_vector)
Translates the current matrix with a Vector2.
Parameters
p_vector : The desired 2D off-set
Returns
The current matrix translated
Definition at line 219 of file Matrix3.inl.
 {
     m_data[2] = p_vector.x;
     m_data[5] = p_vector.y;
     return { *this };
 }
References GPM::Vector2< T >::x, and GPM::Vector2< T >::y.
Transpose() [1/4]
template<typename T> constexpr Matrix3<T>& GPM::Matrix3< T >::Transpose ()
Returns this matrix transposed.
Returns
The same matrix that has its columns exchanged with its rows
Transpose() [2/4]
template<typename T > constexpr Matrix3< T > & Matrix3::Transpose ()
Returns this matrix transposed.
Returns
The same matrix that has its columns exchanged with its rows
Definition at line 121 of file Matrix3.inl.
 {
     Matrix3<T> tmpMat(this->m_data);
     for (int n = 0; n < 9; n++)
     {
         int i = n / 3;
         int j = n % 3;
         m_data[n] = tmpMat.m_data[3 * j + i];
     }
     return {*this};
 }
References GPM::Matrix3< T >::m_data.
Transpose() [3/4]
template<typename T> static constexpr Matrix3<T> GPM::Matrix3< T >::Transpose (const Matrix3< T > & p_matrix3) static
Returns this matrix transposed.
Parameters
p_matrix3 : The matrix to get the Transpose from
Returns
The same matrix that has its columns exchanged with its rows
Transpose() [4/4]
template<typename T > constexpr Matrix3< T > Matrix3::Transpose (const Matrix3< T > & p_matrix3) static
Returns this matrix transposed.
Parameters
p_matrix3 : The matrix to get the Transpose from
Returns
The same matrix that has its columns exchanged with its rows
Definition at line 136 of file Matrix3.inl.
 {
     Matrix3<T> tmpMat = identity;
     for (int n = 0; n < 9; n++)
     {
         int i = n / 3;
         int j = n % 3;
         tmpMat.m_data[n] = p_matrix3.m_data[3 * j + i];
     }
     return tmpMat;
 }
References GPM::Matrix3< T >::m_data.
Field Documentation
identity
template<typename T> Matrix3< T > Matrix3::identity static
Initial value:
= { 1,0,0,
                                    0,1,0,
                                    0,0,1 }
This is a const matrix that has 1 in the diagonal and 0 elsewhere.
Definition at line 104 of file Matrix3.h.
m_data
template<typename T> T GPM::Matrix3< T >::m_data
Initial value:
= { 1,0,0,
                        0,1,0,
                        0,0,1 }
Definition at line 15 of file Matrix3.h.
Referenced by GPM::Matrix3< T >::Add(), GPM::Matrix3< T >::CreateRotation(), GPM::Matrix3< T >::CreateScaling(), GPM::Matrix3< T >::CreateTranslation(), GPM::Matrix3< T >::Determinant(), GPM::Matrix3< T >::Equals(), GPM::Matrix4< T >::GetMinor(), GPM::Matrix3< T >::Matrix3(), GPM::Matrix3< T >::Multiply(), GPM::Matrix3< T >::operator=(), GPM::Matrix3< T >::Subtract(), GPM::Quaternion::ToMatrix3(), GPM::Matrix3< T >::ToString(), and GPM::Matrix3< T >::Transpose().
zero
template<typename T> Matrix3< T > Matrix3::zero static
Initial value:
= { 0,0,0,
                                0,0,0,
                                0,0,0 }
This is a const matrix that has 0 everywhere.
Definition at line 109 of file Matrix3.h.
The documentation for this struct was generated from the following files:
GPM/include/GPM/Matrix/Matrix3.h
GPM/include/GPM/Matrix/Matrix3.inl