GPM: GPM::Vector4< T > Struct Template Reference
GPM::Vector4< T > Struct Template Reference final
#include <Vector4.h>
Public Member Functions
constexpr Vector4 ()
Default Constructor.
~Vector4 ()=default
Destructor.
constexpr Vector4 (const T p_x, const T p_y, const T p_z, const T p_w=1.0f)
Constructor with parameters.
constexpr Vector4 (const Vector3< T > &p_other)
Constructor from vector3.
constexpr Vector4 (Vector3< T > &&p_other)
Move Constructor from vector3.
constexpr Vector4 (const Vector4< T > &p_other)
Copy Constructor.
constexpr Vector4 (Vector4< T > &&p_other) noexcept
Move Constructor.
constexpr Vector4< T > & operator= (const Vector4< T > &p_other)
Overload = operator by copy.
constexpr Vector4< T > & operator= (Vector4< T > &&p_other) noexcept
Overload = operator by move.
constexpr bool IsParallelTo (const Vector4< T > &p_other) const
Return true if the two vectors are parallel.
constexpr bool IsPerpendicularTo (const Vector4< T > &p_other) const
Return true if the two vectors are perpendicular.
constexpr bool IsHomogenized () const
Return true if the vector is homogenized.
constexpr bool IsEqualTo (const Vector4< T > &p_other) const
Return true if the two vectors are identical.
constexpr bool operator== (const Vector4< T > &p_other) const
Return true if the two vectors are identical.
Vector4< T > & Add (const T p_scalar)
Add scalar to x, y and z.
template<typename U >
Vector4< T > & Add (const U p_scalar)
Add scalar to x, y and z.
Vector4< T > & Add (const Vector4< T > &p_other)
Add other vector to the actual vector.
template<typename U >
Vector4< T > & Add (const Vector4< U > &p_other)
Add other vector to the actual vector.
constexpr Vector4< T > operator+ (const T p_scalar) const
Return the summation of other vector and actual vector.
Vector4< T > & operator+= (const T p_scalar)
Add other vector to the actual vector.
constexpr Vector4< T > operator+ (const Vector4< T > &p_other) const
Return the summation of other vector and actual vector.
template<typename U >
constexpr Vector4< T > operator+ (const Vector4< U > &p_other) const
Return the summation of other vector and actual vector.
Vector4< T > & operator+= (const Vector4< T > &p_other)
Add other vector to the actual vector.
template<typename U >
Vector4< T > & operator+= (const Vector4< U > &p_other)
Add other vector to the actual vector.
Vector4< T > & Subtract (const T p_scalar)
Subtract scalar to x, y and z.
template<typename U >
Vector4< T > & Subtract (const U p_scalar)
Subtract scalar to x, y and z.
Vector4< T > & Subtract (const Vector4< T > &p_other)
Subtract other vector to the actual vector.
template<typename U >
Vector4< T > & Subtract (const Vector4< U > &p_other)
Subtract other vector to the actual vector.
constexpr Vector4< T > operator- (const T p_scalar) const
Return the subtraction of other vector and actual vector.
Vector4< T > & operator-= (const T p_scalar)
Subtract other vector to the actual vector.
constexpr Vector4< T > operator- (const Vector4< T > &p_other) const
Return the subtraction of other vector and actual vector.
template<typename U >
constexpr Vector4< T > operator- (const Vector4< U > &p_other) const
Return the subtraction of other vector and actual vector.
Vector4< T > & operator-= (const Vector4< T > &p_other)
Subtract other vector to the actual vector.
template<typename U >
Vector4< T > & operator-= (const Vector4< U > &p_other)
Subtract other vector to the actual vector.
Vector4< T > & Multiply (const T p_scalar)
Multiply scalar to x, y and z.
template<typename U >
Vector4< T > & Multiply (const U p_scalar)
Multiply scalar to x, y and z.
Vector4< T > & Multiply (const Vector4< T > &p_other)
Multiply other vector to the actual vector.
template<typename U >
Vector4< T > & Multiply (const Vector4< U > &p_other)
Multiply other vector to the actual vector.
constexpr Vector4< T > operator * (const T p_scalar) const
Return the multiplication of scalar and actual vector.
Vector4< T > & operator *= (const T p_scalar)
Multiply scalar to the actual vector.
constexpr Vector4< T > operator * (const Vector4< T > &p_other) const
Return the multiplication of a vector and actual vector.
template<typename U >
constexpr Vector4< T > operator * (const Vector4< U > &p_other) const
Return the multiplication of a vector and actual vector.
Vector4< T > & operator *= (const Vector4< T > &p_other)
Multiply vector to the actual vector.
template<typename U >
Vector4< T > & operator *= (const Vector4< U > &p_other)
Multiply vector to the actual vector.
Vector4< T > & Divide (const T p_scalar)
Divide scalar to x, y and z.
template<typename U >
Vector4< T > & Divide (const U p_scalar)
Divide scalar to x, y and z.
Vector4< T > & Divide (const Vector4< T > &p_other)
Divide other vector to the actual vector.
template<typename U >
Vector4< T > & Divide (const Vector4< U > &p_other)
Divide other vector to the actual vector.
constexpr Vector4< T > operator/ (const T p_scalar) const
Return the division of scalar and actual vector.
Vector4< T > & operator/= (const T p_scalar)
Divide scalar to the actual vector.
constexpr Vector4< T > operator/ (const Vector4< T > &p_other) const
Return the division of a vector and actual vector.
template<typename U >
constexpr Vector4< T > operator/ (const Vector4< U > &p_other) const
Return the division of a vector and actual vector.
Vector4< T > & operator/= (const Vector4< T > &p_other)
Divide vector to the actual vector.
template<typename U >
Vector4< T > & operator/= (const Vector4< U > &p_other)
Divide vector to the actual vector.
constexpr float Distance (const Vector4< T > &p_vector) const
Calculate the distance between the vector and another.
constexpr Vector4< T > & Scale (const T p_scale) const
Scale the vector with scalar.
constexpr T Magnitude () const
Calculate the length of the vector.
constexpr T MagnitudeSquare () const
Calculate the squared length of the vector.
constexpr T Dot (const Vector4< T > &p_other) const
Calculate the dot product with other vector.
constexpr Vector4< T > Cross (const Vector4< T > &p_other) const
Calculate the cross product with other vector.
constexpr T Angle (const Vector4< T > &p_other) const
Calculate the angle between two vectors in radiant.
Vector4< T > & Normalize ()
Normalize the vector.
Vector4< T > & Homogenize ()
Homogenize the vector.
constexpr std::string ToString () const
Convert vector to string.
constexpr Vector4 ()
Default Constructor.
~Vector4 ()=default
Destructor.
constexpr Vector4 (const T p_x, const T p_y, const T p_z, const T p_w=1.0f)
Constructor with parameters.
constexpr Vector4 (const Vector3< T > &p_other)
Constructor from vector3.
constexpr Vector4 (Vector3< T > &&p_other)
Move Constructor from vector3.
constexpr Vector4 (const Vector4< T > &p_other)
Copy Constructor.
constexpr Vector4 (Vector4< T > &&p_other) noexcept
Move Constructor.
constexpr Vector4< T > & operator= (const Vector4< T > &p_other)
Overload = operator by copy.
constexpr Vector4< T > & operator= (Vector4< T > &&p_other) noexcept
Overload = operator by move.
constexpr bool IsParallelTo (const Vector4< T > &p_other) const
Return true if the two vectors are parallel.
constexpr bool IsPerpendicularTo (const Vector4< T > &p_other) const
Return true if the two vectors are perpendicular.
constexpr bool IsHomogenized () const
Return true if the vector is homogenized.
constexpr bool IsEqualTo (const Vector4< T > &p_other) const
Return true if the two vectors are identical.
constexpr bool operator== (const Vector4< T > &p_other) const
Return true if the two vectors are identical.
Vector4< T > & Add (const T p_scalar)
Add scalar to x, y and z.
template<typename U >
Vector4< T > & Add (const U p_scalar)
Add scalar to x, y and z.
Vector4< T > & Add (const Vector4< T > &p_other)
Add other vector to the actual vector.
template<typename U >
Vector4< T > & Add (const Vector4< U > &p_other)
Add other vector to the actual vector.
constexpr Vector4< T > operator+ (const T p_scalar) const
Return the summation of other vector and actual vector.
Vector4< T > & operator+= (const T p_scalar)
Add other vector to the actual vector.
constexpr Vector4< T > operator+ (const Vector4< T > &p_other) const
Return the summation of other vector and actual vector.
template<typename U >
constexpr Vector4< T > operator+ (const Vector4< U > &p_other) const
Return the summation of other vector and actual vector.
Vector4< T > & operator+= (const Vector4< T > &p_other)
Add other vector to the actual vector.
template<typename U >
Vector4< T > & operator+= (const Vector4< U > &p_other)
Add other vector to the actual vector.
Vector4< T > & Subtract (const T p_scalar)
Subtract scalar to x, y and z.
template<typename U >
Vector4< T > & Subtract (const U p_scalar)
Subtract scalar to x, y and z.
Vector4< T > & Subtract (const Vector4< T > &p_other)
Subtract other vector to the actual vector.
template<typename U >
Vector4< T > & Subtract (const Vector4< U > &p_other)
Subtract other vector to the actual vector.
constexpr Vector4< T > operator- (const T p_scalar) const
Return the subtraction of other vector and actual vector.
Vector4< T > & operator-= (const T p_scalar)
Subtract other vector to the actual vector.
constexpr Vector4< T > operator- (const Vector4< T > &p_other) const
Return the subtraction of other vector and actual vector.
template<typename U >
constexpr Vector4< T > operator- (const Vector4< U > &p_other) const
Return the subtraction of other vector and actual vector.
Vector4< T > & operator-= (const Vector4< T > &p_other)
Subtract other vector to the actual vector.
template<typename U >
Vector4< T > & operator-= (const Vector4< U > &p_other)
Subtract other vector to the actual vector.
Vector4< T > & Multiply (const T p_scalar)
Multiply scalar to x, y and z.
template<typename U >
Vector4< T > & Multiply (const U p_scalar)
Multiply scalar to x, y and z.
Vector4< T > & Multiply (const Vector4< T > &p_other)
Multiply other vector to the actual vector.
template<typename U >
Vector4< T > & Multiply (const Vector4< U > &p_other)
Multiply other vector to the actual vector.
constexpr Vector4< T > operator * (const T p_scalar) const
Return the multiplication of scalar and actual vector.
Vector4< T > & operator *= (const T p_scalar)
Multiply scalar to the actual vector.
constexpr Vector4< T > operator * (const Vector4< T > &p_other) const
Return the multiplication of a vector and actual vector.
template<typename U >
constexpr Vector4< T > operator * (const Vector4< U > &p_other) const
Return the multiplication of a vector and actual vector.
Vector4< T > & operator *= (const Vector4< T > &p_other)
Multiply vector to the actual vector.
template<typename U >
Vector4< T > & operator *= (const Vector4< U > &p_other)
Multiply vector to the actual vector.
Vector4< T > & Divide (const T p_scalar)
Divide scalar to x, y and z.
template<typename U >
Vector4< T > & Divide (const U p_scalar)
Divide scalar to x, y and z.
Vector4< T > & Divide (const Vector4< T > &p_other)
Divide other vector to the actual vector.
template<typename U >
Vector4< T > & Divide (const Vector4< U > &p_other)
Divide other vector to the actual vector.
constexpr Vector4< T > operator/ (const T p_scalar) const
Return the division of scalar and actual vector.
Vector4< T > & operator/= (const T p_scalar)
Divide scalar to the actual vector.
constexpr Vector4< T > operator/ (const Vector4< T > &p_other) const
Return the division of a vector and actual vector.
template<typename U >
constexpr Vector4< T > operator/ (const Vector4< U > &p_other) const
Return the division of a vector and actual vector.
Vector4< T > & operator/= (const Vector4< T > &p_other)
Divide vector to the actual vector.
template<typename U >
Vector4< T > & operator/= (const Vector4< U > &p_other)
Divide vector to the actual vector.
constexpr float Distance (const Vector4< T > &p_vector) const
Calculate the distance between the vector and another.
constexpr Vector4< T > & Scale (const T p_scale) const
Scale the vector with scalar.
constexpr T Magnitude () const
Calculate the length of the vector.
constexpr T MagnitudeSquare () const
Calculate the squared length of the vector.
constexpr T Dot (const Vector4< T > &p_other) const
Calculate the dot product with other vector.
constexpr Vector4< T > Cross (const Vector4< T > &p_other) const
Calculate the cross product with other vector.
constexpr T Angle (const Vector4< T > &p_other) const
Calculate the angle between two vectors in radiant.
Vector4< T > & Normalize ()
Normalize the vector.
Vector4< T > & Homogenize ()
Homogenize the vector.
constexpr std::string ToString () const
Convert vector to string.
Static Public Member Functions
static constexpr bool AreParallel (const Vector4< T > &p_left, const Vector4< T > &p_right)
Return true if the two vectors are parallel.
static constexpr bool ArePerpendicular (const Vector4< T > &p_left, const Vector4< T > &p_right)
Return true if the two vectors are perpendicular.
static constexpr bool IsHomogenized (const Vector4< T > &p_vector)
Return true if the vector is homogenized.
static constexpr bool AreEqual (const Vector4< T > &p_left, const Vector4< T > &p_right)
Return true if the two vectors are identical.
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const T p_scalar)
Add scalar to vector left.
template<typename U >
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const U p_scalar)
Add scalar to vector left.
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const Vector4< T > &p_right)
Add left vector to the right vector.
template<typename U >
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const Vector4< U > &p_right)
Add left vector to the right vector.
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const T p_scalar)
Subtract scalar to vector left.
template<typename U >
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const U p_scalar)
Subtract scalar to vector left.
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const Vector4< T > &p_right)
Subtract left vector to the right vector.
template<typename U >
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const Vector4< U > &p_right)
Subtract left vector to the right vector.
static constexpr Vector4< T > Multiply (const Vector4< T > &p_left, T p_scalar)
Multiply scalar to vector left.
template<typename U >
static constexpr Vector4< T > Multiply (const Vector4< T > &p_left, U p_scalar)
Multiply scalar to vector left.
static constexpr Vector4< T > Divide (const Vector4< T > &p_left, const T p_scalar)
Divide scalar to vector left.
template<typename U >
static constexpr Vector4< T > Divide (const Vector4< T > &p_left, const U p_scalar)
Divide scalar to vector left.
static constexpr float Distance (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the distance between the vector and another.
static constexpr Vector4< T > Scale (const Vector4< T > &p_vector, const T p_scale)
Calculate the distance between the vector and another.
static constexpr T Magnitude (const Vector4< T > &p_vector)
Calculate the length of the vector.
static constexpr T MagnitudeSquare (const Vector4< T > &p_vector)
Calculate the squared length of the vector.
static constexpr T Dot (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the dot product between two vectors.
static constexpr Vector4< T > Cross (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the cross product between two vectors.
static constexpr T TripleProduct (const Vector4< T > &p_left, const Vector4< T > &p_middle, const Vector4< T > &p_right)
Calculate the dot product between left and the result of cross product between middle and right.
static constexpr T Angle (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the angle between two vectors in radiant.
static constexpr Vector4< T > Normalize (const Vector4< T > &p_vector)
Return the normalized vector.
static constexpr Vector4< T > Homogenize (const Vector4< T > &p_vector)
Return the homogenized vector.
static constexpr Vector4< T > Lerp (const Vector4< T > &p_start, const Vector4< T > &p_end, const float p_interpolationCoefficient)
Return the start vector moving to the end vector at step interpolationCoefficient.
static constexpr Vector4< T > Slerp (const Vector4< T > &p_start, const Vector4< T > &p_end, const float p_interpolationCoefficient)
Return the start vector moving to the end vector at step interpolationCoefficient.
static constexpr Vector4< T > Nlerp (const Vector4< T > &p_start, const Vector4< T > &p_end, const float p_interpolationCoefficient)
Return the start vector moving to the end vector at step interpolationCoefficient.
static constexpr std::string ToString (const Vector4< T > &p_vector)
Convert vector to string.
static constexpr bool AreParallel (const Vector4< T > &p_left, const Vector4< T > &p_right)
Return true if the two vectors are parallel.
static constexpr bool ArePerpendicular (const Vector4< T > &p_left, const Vector4< T > &p_right)
Return true if the two vectors are perpendicular.
static constexpr bool IsHomogenized (const Vector4< T > &p_vector)
Return true if the vector is homogenized.
static constexpr bool AreEqual (const Vector4< T > &p_left, const Vector4< T > &p_right)
Return true if the two vectors are identical.
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const T p_scalar)
Add scalar to vector left.
template<typename U >
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const U p_scalar)
Add scalar to vector left.
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const Vector4< T > &p_right)
Add left vector to the right vector.
template<typename U >
static constexpr Vector4< T > Add (const Vector4< T > &p_left, const Vector4< U > &p_right)
Add left vector to the right vector.
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const T p_scalar)
Subtract scalar to vector left.
template<typename U >
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const U p_scalar)
Subtract scalar to vector left.
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const Vector4< T > &p_right)
Subtract left vector to the right vector.
template<typename U >
static constexpr Vector4< T > Subtract (const Vector4< T > &p_left, const Vector4< U > &p_right)
Subtract left vector to the right vector.
static constexpr Vector4< T > Multiply (const Vector4< T > &p_left, T p_scalar)
Multiply scalar to vector left.
template<typename U >
static constexpr Vector4< T > Multiply (const Vector4< T > &p_left, U p_scalar)
Multiply scalar to vector left.
static constexpr Vector4< T > Divide (const Vector4< T > &p_left, const T p_scalar)
Divide scalar to vector left.
template<typename U >
static constexpr Vector4< T > Divide (const Vector4< T > &p_left, const U p_scalar)
Divide scalar to vector left.
static constexpr float Distance (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the distance between the vector and another.
static constexpr Vector4< T > Scale (const Vector4< T > &p_vector, const T p_scale)
Calculate the distance between the vector and another.
static constexpr T Magnitude (const Vector4< T > &p_vector)
Calculate the length of the vector.
static constexpr T MagnitudeSquare (const Vector4< T > &p_vector)
Calculate the squared length of the vector.
static constexpr T Dot (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the dot product between two vectors.
static constexpr Vector4< T > Cross (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the cross product between two vectors.
static constexpr T TripleProduct (const Vector4< T > &p_left, const Vector4< T > &p_middle, const Vector4< T > &p_right)
Calculate the dot product between left and the result of cross product between middle and right.
static constexpr T Angle (const Vector4< T > &p_left, const Vector4< T > &p_right)
Calculate the angle between two vectors in radiant.
static constexpr Vector4< T > Normalize (const Vector4< T > &p_vector)
Return the normalized vector.
static constexpr Vector4< T > Homogenize (const Vector4< T > &p_vector)
Return the homogenized vector.
static constexpr Vector4< T > Lerp (const Vector4< T > &p_start, const Vector4< T > &p_end, const float p_interpolationCoefficient)
Return the start vector moving to the end vector at step interpolationCoefficient.
static constexpr Vector4< T > Slerp (const Vector4< T > &p_start, const Vector4< T > &p_end, const float p_interpolationCoefficient)
Return the start vector moving to the end vector at step interpolationCoefficient.
static constexpr Vector4< T > Nlerp (const Vector4< T > &p_start, const Vector4< T > &p_end, const float p_interpolationCoefficient)
Return the start vector moving to the end vector at step interpolationCoefficient.
static constexpr std::string ToString (const Vector4< T > &p_vector)
Convert vector to string.
Data Fields
T x
T y
T z
T w
Static Public Attributes
static const Vector4< T > zero = Vector4<T>(0, 0, 0, 1)
static const Vector4< T > one = Vector4<T>(1, 1, 1, 1)
static const Vector4< T > xAxis = Vector4<T>(1, 0, 0, 1)
static const Vector4< T > yAxis = Vector4<T>(0, 1, 0, 1)
static const Vector4< T > zAxis = Vector4<T>(0, 0, 1, 1)
Detailed Description
template<typename T>
struct GPM::Vector4< T >
Definition at line 11 of file Vector4.h.
Constructor & Destructor Documentation
Vector4() [1/12]
template<typename T > constexpr GPM::Vector4< T >::Vector4 ()
Default Constructor.
Definition at line 22 of file Vector4.inl.
         : x{ 0 }, y{ 0 }, z{ 0 }, w{ 1 } {}
~Vector4() [1/2]
template<typename T> GPM::Vector4< T >::~Vector4 () default
Destructor.
Vector4() [2/12]
template<typename T > constexpr GPM::Vector4< T >::Vector4 (const T p_x, const T p_y, const T p_z, const T p_w = 1.0f)
Constructor with parameters.
Parameters
p_x x coordinate
p_y y coordinate
p_z z coordinate
p_w Set to 1 for vectors, 0 for points
Definition at line 26 of file Vector4.inl.
         : x{ p_x }, y{ p_y }, z{ p_z }, w{ p_w } {}
Vector4() [3/12]
template<typename T > constexpr GPM::Vector4< T >::Vector4 (const Vector3< T > & p_other) explicit
Constructor from vector3.
Parameters
p_other The vector to construct from
Definition at line 30 of file Vector4.inl.
         : x{ p_other.x }, y{ p_other.y }, z{ p_other.z }, w{ 1 } {}
References GPM::Vector3< T >::x.
Vector4() [4/12]
template<typename T > constexpr GPM::Vector4< T >::Vector4 (Vector3< T > && p_other) explicit
Move Constructor from vector3.
Parameters
p_other The vector to construct from
Definition at line 34 of file Vector4.inl.
         : x{ p_other.x }, y{ p_other.y }, z{ p_other.z }, w{ 1 } {}
Vector4() [5/12]
template<typename T > constexpr GPM::Vector4< T >::Vector4 (const Vector4< T > & p_other)
Copy Constructor.
Parameters
p_other The vector to construct from
Definition at line 38 of file Vector4.inl.
     {
         *this = p_other;
     }
Vector4() [6/12]
template<typename T > constexpr GPM::Vector4< T >::Vector4 (Vector4< T > && p_other) noexcept
Move Constructor.
Parameters
p_other The vector to construct from
Definition at line 44 of file Vector4.inl.
     {
         *this = p_other;
     }
Vector4() [7/12]
template<typename T> constexpr GPM::Vector4< T >::Vector4 ()
Default Constructor.
~Vector4() [2/2]
template<typename T> GPM::Vector4< T >::~Vector4 () default
Destructor.
Vector4() [8/12]
template<typename T> constexpr GPM::Vector4< T >::Vector4 (const T p_x, const T p_y, const T p_z, const T p_w = 1.0f)
Constructor with parameters.
Parameters
p_x x coordinate
p_y y coordinate
p_z z coordinate
p_w Set to 1 for vectors, 0 for points
Vector4() [9/12]
template<typename T> constexpr GPM::Vector4< T >::Vector4 (const Vector3< T > & p_other) explicit
Constructor from vector3.
Parameters
p_other The vector to construct from
Vector4() [10/12]
template<typename T> constexpr GPM::Vector4< T >::Vector4 (Vector3< T > && p_other) explicit
Move Constructor from vector3.
Parameters
p_other The vector to construct from
Vector4() [11/12]
template<typename T> constexpr GPM::Vector4< T >::Vector4 (const Vector4< T > & p_other)
Copy Constructor.
Parameters
p_other The vector to construct from
Vector4() [12/12]
template<typename T> constexpr GPM::Vector4< T >::Vector4 (Vector4< T > && p_other) noexcept
Move Constructor.
Parameters
p_other The vector to construct from
Member Function Documentation
Add() [1/16]
template<typename T > Vector4< T > & GPM::Vector4< T >::Add (const T p_scalar)
Add scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 135 of file Vector4.inl.
     {
         x += p_scalar;
         y += p_scalar;
         z += p_scalar;
         return { *this };
     }
Referenced by GPM::Vector4< T >::Add(), and GPM::Vector4< T >::operator+().
Add() [2/16]
template<typename T> Vector4<T>& GPM::Vector4< T >::Add (const T p_scalar)
Add scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Add() [3/16]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Add (const U p_scalar)
Add scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 146 of file Vector4.inl.
     {
         x += p_scalar;
         y += p_scalar;
         z += p_scalar;
         return { *this };
     }
Add() [4/16]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Add (const U p_scalar)
Add scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Add() [5/16]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Add (const Vector4< T > & p_left, const T p_scalar) static
Add scalar to vector left.
Parameters
p_left The left vector to add
p_scalar The scalar
Returns
The result vector
Add() [6/16]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Add (const Vector4< T > & p_left, const T p_scalar) static
Add scalar to vector left.
Parameters
p_left The left vector to add
p_scalar The scalar
Returns
The result vector
Definition at line 156 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Add(p_scalar) };
     }
References GPM::Vector4< T >::Add().
Add() [7/16]
template<typename T> template<typename U > static constexpr Vector4<T> GPM::Vector4< T >::Add (const Vector4< T > & p_left, const U p_scalar) static
Add scalar to vector left.
Parameters
p_left The left vector to add
p_scalar The scalar
Returns
The result vector
Add() [8/16]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::Add (const Vector4< T > & p_left, const U p_scalar) static
Add scalar to vector left.
Parameters
p_left The left vector to add
p_scalar The scalar
Returns
The result vector
Definition at line 163 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Add(p_scalar) };
     }
References GPM::Vector4< T >::Add().
Add() [9/16]
template<typename T > Vector4< T > & GPM::Vector4< T >::Add (const Vector4< T > & p_other)
Add other vector to the actual vector.
Parameters
p_other The vector to add
Returns
The current vector modified
Definition at line 169 of file Vector4.inl.
     {
         x += p_other.x;
         y += p_other.y;
         z += p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Add() [10/16]
template<typename T> Vector4<T>& GPM::Vector4< T >::Add (const Vector4< T > & p_other)
Add other vector to the actual vector.
Parameters
p_other The vector to add
Returns
The current vector modified
Add() [11/16]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Add (const Vector4< U > & p_other)
Add other vector to the actual vector.
Parameters
p_other The vector to add
Returns
The current vector modified
Definition at line 180 of file Vector4.inl.
     {
         x += p_other.x;
         y += p_other.y;
         z += p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Add() [12/16]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Add (const Vector4< U > & p_other)
Add other vector to the actual vector.
Parameters
p_other The vector to add
Returns
The current vector modified
Add() [13/16]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Add (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Add left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Definition at line 190 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Add(p_right) };
     }
References GPM::Vector4< T >::Add().
Add() [14/16]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Add (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Add left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Add() [15/16]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::Add (const Vector4< T > & p_left, const Vector4< U > & p_right) static
Add left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Definition at line 197 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Add(p_right) };
     }
References GPM::Vector4< T >::Add().
Add() [16/16]
template<typename T> template<typename U > static constexpr Vector4<T> GPM::Vector4< T >::Add (const Vector4< T > & p_left, const Vector4< U > & p_right) static
Add left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Angle() [1/4]
template<typename T > constexpr T GPM::Vector4< T >::Angle (const Vector4< T > & p_other) const
Calculate the angle between two vectors in radiant.
Parameters
p_other The vector to lookup for angle
Returns
The angle between the two vectors
Definition at line 665 of file Vector4.inl.
     {
         if (w == 0 || p_other.w == 0)
             throw std::logic_error("Can't Compute angle, one of the params is a point: W = 0");
         const float dotProduct = Dot(p_other);
         const T lengthProduct = Magnitude() * p_other.Magnitude();
         const T fractionResult = dotProduct / lengthProduct;
         if (fractionResult > -1 && fractionResult < 1)
             return { static_cast<T>(Tools::Utils::Arccos(fractionResult)) };
         return 0;
     }
References GPM::Tools::Utils::Arccos(), GPM::Vector4< T >::Magnitude(), and GPM::Vector4< T >::w.
Referenced by GPM::Vector4< T >::Angle(), and GPM::Vector4< T >::Slerp().
Angle() [2/4]
template<typename T> constexpr T GPM::Vector4< T >::Angle (const Vector4< T > & p_other) const
Calculate the angle between two vectors in radiant.
Parameters
p_other The vector to lookup for angle
Returns
The angle between the two vectors
Angle() [3/4]
template<typename T > constexpr T GPM::Vector4< T >::Angle (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the angle between two vectors in radiant.
Parameters
p_left The left vector
p_right The right vector
Returns
The angle between the two vectors
Definition at line 682 of file Vector4.inl.
     {
         return  { p_left.Angle(p_right) };
     }
References GPM::Vector4< T >::Angle().
Angle() [4/4]
template<typename T> static constexpr T GPM::Vector4< T >::Angle (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the angle between two vectors in radiant.
Parameters
p_left The left vector
p_right The right vector
Returns
The angle between the two vectors
AreEqual() [1/2]
template<typename T> static constexpr bool GPM::Vector4< T >::AreEqual (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Return true if the two vectors are identical.
Parameters
p_left The left vector
p_right The right vector
Returns
True or false
AreEqual() [2/2]
template<typename T > constexpr bool GPM::Vector4< T >::AreEqual (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Return true if the two vectors are identical.
Parameters
p_left The left vector
p_right The right vector
Returns
True or false
Definition at line 118 of file Vector4.inl.
     {
         return { p_left.IsEqualTo(p_right) };
     }
References GPM::Vector4< T >::IsEqualTo().
AreParallel() [1/2]
template<typename T > constexpr bool GPM::Vector4< T >::AreParallel (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Return true if the two vectors are parallel.
Parameters
p_left The left vector
p_right The right vector
Returns
True or false
Definition at line 82 of file Vector4.inl.
     {
         return  { p_left.IsParallelTo(p_right) };
     }
References GPM::Vector4< T >::IsParallelTo().
AreParallel() [2/2]
template<typename T> static constexpr bool GPM::Vector4< T >::AreParallel (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Return true if the two vectors are parallel.
Parameters
p_left The left vector
p_right The right vector
Returns
True or false
ArePerpendicular() [1/2]
template<typename T> static constexpr bool GPM::Vector4< T >::ArePerpendicular (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Return true if the two vectors are perpendicular.
Parameters
p_left The left vector
p_right The right vector
Returns
True or false
ArePerpendicular() [2/2]
template<typename T > constexpr bool GPM::Vector4< T >::ArePerpendicular (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Return true if the two vectors are perpendicular.
Parameters
p_left The left vector
p_right The right vector
Returns
True or false
Definition at line 94 of file Vector4.inl.
     {
         return  { p_left.IsPerpendicularTo(p_right) };
     }
References GPM::Vector4< T >::IsPerpendicularTo().
Cross() [1/4]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Cross (const Vector4< T > & p_other) const
Calculate the cross product with other vector.
Parameters
p_other The other vector for cross product
Returns
The result vector
Definition at line 634 of file Vector4.inl.
     {
         Vector4<T> result;
         if (w == 0 || p_other.w == 0)
             throw std::logic_error("Can't Compute Cross, one of the params is a point: W = 0");
         const Vector4<T> right = Vector4<T>::Homogenize(*this);
         const Vector4<T> left = Vector4<T>::Homogenize(p_other);
         result.x = right.y * left.z - right.z * left.y;
         result.y = right.z * left.x - right.x * left.z;
         result.z = right.x * left.y - right.y * left.x;
         return { result };
     }
References GPM::Vector4< T >::Homogenize(), GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Referenced by GPM::Vector4< T >::Cross().
Cross() [2/4]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::Cross (const Vector4< T > & p_other) const
Calculate the cross product with other vector.
Parameters
p_other The other vector for cross product
Returns
The result vector
Cross() [3/4]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Cross (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the cross product between two vectors.
Parameters
p_left Left vector
p_right Right vector
Returns
The result vector
Definition at line 652 of file Vector4.inl.
     {
         return p_left.Cross(p_right);
     }
References GPM::Vector4< T >::Cross().
Cross() [4/4]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Cross (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the cross product between two vectors.
Parameters
p_left Left vector
p_right Right vector
Returns
The result vector
Distance() [1/4]
template<typename T > constexpr float GPM::Vector4< T >::Distance (const Vector4< T > & p_vector) const
Calculate the distance between the vector and another.
Parameters
p_vector The vector to compare distance
Returns
The distance
Definition at line 559 of file Vector4.inl.
     {
         if (w != 0 || p_vector.w != 0)
             throw std::logic_error("Can't Compute Distance, one of the params is a direction: W != 0");
         return Tools::Utils::SquareRootF((x - p_vector.x * x - p_vector.x) + (y - p_vector.y) * (y - p_vector.y) + (z - p_vector.z) * (z - p_vector.z));
     }
References GPM::Tools::Utils::SquareRootF(), GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Distance() [2/4]
template<typename T> constexpr float GPM::Vector4< T >::Distance (const Vector4< T > & p_vector) const
Calculate the distance between the vector and another.
Parameters
p_vector The vector to compare distance
Returns
The distance
Distance() [3/4]
template<typename T > constexpr float GPM::Vector4< T >::Distance (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the distance between the vector and another.
Parameters
p_left The left vector
p_right The right vector
Returns
The distance
Definition at line 568 of file Vector4.inl.
     {
         if (p_left.w != 0 || p_right.w != 0)
             throw std::logic_error("Can't Compute Distance, one of the params is a point: W != 0");
         return Tools::Utils::SquareRootF((p_left.x - p_right.x * p_left.x - p_right.x) + (p_left.y - p_right.y) * (p_left.y - p_right.y) + (p_left.z - p_right.z) * (p_left.z - p_right.z));
     }
References GPM::Tools::Utils::SquareRootF(), GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Distance() [4/4]
template<typename T> static constexpr float GPM::Vector4< T >::Distance (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the distance between the vector and another.
Parameters
p_left The left vector
p_right The right vector
Returns
The distance
Divide() [1/12]
template<typename T> Vector4<T>& GPM::Vector4< T >::Divide (const T p_scalar)
Divide scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Divide() [2/12]
template<typename T > Vector4< T > & GPM::Vector4< T >::Divide (const T p_scalar)
Divide scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 449 of file Vector4.inl.
     {
         if (p_scalar == 0)
             throw std::logic_error("Division by 0");
         x /= p_scalar;
         y /= p_scalar;
         z /= p_scalar;
         return { *this };
     }
Referenced by GPM::Vector4< T >::Divide(), and GPM::Vector4< T >::operator/().
Divide() [3/12]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Divide (const U p_scalar)
Divide scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Divide() [4/12]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Divide (const U p_scalar)
Divide scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 463 of file Vector4.inl.
     {
         if (p_scalar == 0)
             throw std::logic_error("Division by 0");
         x /= p_scalar;
         y /= p_scalar;
         z /= p_scalar;
         return { *this };
     }
Divide() [5/12]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Divide (const Vector4< T > & p_left, const T p_scalar) static
Divide scalar to vector left.
Parameters
p_left The vector to divide
p_scalar The scalar
Returns
The result vector
Divide() [6/12]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Divide (const Vector4< T > & p_left, const T p_scalar) static
Divide scalar to vector left.
Parameters
p_left The vector to divide
p_scalar The scalar
Returns
The result vector
Definition at line 476 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Divide(p_scalar) };
     }
References GPM::Vector4< T >::Divide().
Divide() [7/12]
template<typename T> template<typename U > static constexpr Vector4<T> GPM::Vector4< T >::Divide (const Vector4< T > & p_left, const U p_scalar) static
Divide scalar to vector left.
Parameters
p_left The vector to divide
p_scalar The scalar
Returns
The result vector
Divide() [8/12]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::Divide (const Vector4< T > & p_left, const U p_scalar) static
Divide scalar to vector left.
Parameters
p_left The vector to divide
p_scalar The scalar
Returns
The result vector
Definition at line 483 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Divide(p_scalar) };
     }
References GPM::Vector4< T >::Divide().
Divide() [9/12]
template<typename T> Vector4<T>& GPM::Vector4< T >::Divide (const Vector4< T > & p_other)
Divide other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Divide() [10/12]
template<typename T > Vector4< T > & GPM::Vector4< T >::Divide (const Vector4< T > & p_other)
Divide other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 489 of file Vector4.inl.
     {
         if (p_other.x == 0 || p_other.y == 0 || p_other.z == 0)
             throw std::logic_error("Division by 0");
         x /= p_other.x;
         y /= p_other.y;
         z /= p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Divide() [11/12]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Divide (const Vector4< U > & p_other)
Divide other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Divide() [12/12]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Divide (const Vector4< U > & p_other)
Divide other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 503 of file Vector4.inl.
     {
         if (p_other.x == 0 || p_other.y == 0 || p_other.z == 0)
             throw std::logic_error("Division by 0");
         x /= p_other.x;
         y /= p_other.y;
         z /= p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Dot() [1/4]
template<typename T > constexpr T GPM::Vector4< T >::Dot (const Vector4< T > & p_other) const
Calculate the dot product with other vector.
Parameters
p_other The other vector for dot product
Returns
The scale between two vectors
Definition at line 619 of file Vector4.inl.
     {
         const Vector4<T> left = Vector4<T>::Homogenize(*this);
         const Vector4<T> right = Vector4<T>::Homogenize(p_other);
         return { left.x * right.x + left.y * right.y + left.z * right.z };
     }
References GPM::Vector4< T >::Homogenize(), GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Referenced by GPM::Vector4< T >::Dot(), GPM::Vector4< T >::Slerp(), and GPM::Vector4< T >::TripleProduct().
Dot() [2/4]
template<typename T> constexpr T GPM::Vector4< T >::Dot (const Vector4< T > & p_other) const
Calculate the dot product with other vector.
Parameters
p_other The other vector for dot product
Returns
The scale between two vectors
Dot() [3/4]
template<typename T > constexpr T GPM::Vector4< T >::Dot (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the dot product between two vectors.
Parameters
p_left The left vector
p_right The right vector
Returns
The scale between two vectors
Definition at line 628 of file Vector4.inl.
     {
         return { p_left.Dot(p_right) };
     }
References GPM::Vector4< T >::Dot().
Dot() [4/4]
template<typename T> static constexpr T GPM::Vector4< T >::Dot (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Calculate the dot product between two vectors.
Parameters
p_left The left vector
p_right The right vector
Returns
The scale between two vectors
Homogenize() [1/4]
template<typename T> Vector4<T>& GPM::Vector4< T >::Homogenize ()
Homogenize the vector.
Returns
The current vector homogenized
Homogenize() [2/4]
template<typename T > Vector4< T > & GPM::Vector4< T >::Homogenize ()
Homogenize the vector.
Returns
The current vector homogenized
Definition at line 709 of file Vector4.inl.
     {
         if (w == 0)
             throw std::logic_error("Can't Homogenize a point: W = 0");
         if (w != 1)
         {
             x /= w;
             y /= w;
             z /= w;
             w = 1;
         }
         return *this;
     }
Referenced by GPM::Vector4< T >::Cross(), GPM::Vector4< T >::Dot(), and GPM::Vector4< T >::Homogenize().
Homogenize() [3/4]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Homogenize (const Vector4< T > & p_vector) static
Return the homogenized vector.
Parameters
p_vector The vector to homogenize
Returns
The result vector
Definition at line 726 of file Vector4.inl.
     {
         return Vector4<T>(p_vector).Homogenize();
     }
References GPM::Vector4< T >::Homogenize().
Homogenize() [4/4]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Homogenize (const Vector4< T > & p_vector) static
Return the homogenized vector.
Parameters
p_vector The vector to homogenize
Returns
The result vector
IsEqualTo() [1/2]
template<typename T > constexpr bool GPM::Vector4< T >::IsEqualTo (const Vector4< T > & p_other) const
Return true if the two vectors are identical.
Parameters
p_other The vector used for the checkup
Returns
True or false
Definition at line 112 of file Vector4.inl.
     {
         return { x == p_other.x && y == p_other.y && z == p_other.z && w == p_other.w };
     }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Referenced by GPM::Vector4< T >::AreEqual().
IsEqualTo() [2/2]
template<typename T> constexpr bool GPM::Vector4< T >::IsEqualTo (const Vector4< T > & p_other) const
Return true if the two vectors are identical.
Parameters
p_other The vector used for the checkup
Returns
True or false
IsHomogenized() [1/4]
template<typename T> constexpr bool GPM::Vector4< T >::IsHomogenized () const
Return true if the vector is homogenized.
Returns
True or false
IsHomogenized() [2/4]
template<typename T > constexpr bool GPM::Vector4< T >::IsHomogenized () const
Return true if the vector is homogenized.
Returns
True or false
Definition at line 100 of file Vector4.inl.
     {
         return { w == 1 };
     }
IsHomogenized() [3/4]
template<typename T > constexpr bool GPM::Vector4< T >::IsHomogenized (const Vector4< T > & p_vector) static
Return true if the vector is homogenized.
Parameters
p_vector The vector used for the checkup
Returns
True or false
Definition at line 106 of file Vector4.inl.
     {
         return { p_vector.w == 1 };
     }
References GPM::Vector4< T >::w.
IsHomogenized() [4/4]
template<typename T> static constexpr bool GPM::Vector4< T >::IsHomogenized (const Vector4< T > & p_vector) static
Return true if the vector is homogenized.
Parameters
p_vector The vector used for the checkup
Returns
True or false
IsParallelTo() [1/2]
template<typename T > constexpr bool GPM::Vector4< T >::IsParallelTo (const Vector4< T > & p_other) const
Return true if the two vectors are parallel.
Parameters
p_other The vector used for the checkup
Returns
True or false
Definition at line 75 of file Vector4.inl.
     {
         return  { Vector4<T>::Normalize(*this) == Vector4<T>::Normalize(p_other) ||
             Vector4<T>::Normalize(*this) == (Vector4<T>::Normalize(p_other) * -1) };
     }
References GPM::Vector4< T >::Normalize().
Referenced by GPM::Vector4< T >::AreParallel().
IsParallelTo() [2/2]
template<typename T> constexpr bool GPM::Vector4< T >::IsParallelTo (const Vector4< T > & p_other) const
Return true if the two vectors are parallel.
Parameters
p_other The vector used for the checkup
Returns
True or false
IsPerpendicularTo() [1/2]
template<typename T > constexpr bool GPM::Vector4< T >::IsPerpendicularTo (const Vector4< T > & p_other) const
Return true if the two vectors are perpendicular.
Parameters
p_other The vector used for the checkup
Returns
True or false
Definition at line 88 of file Vector4.inl.
     {
         return { Dot(p_other) == 0 };
     }
Referenced by GPM::Vector4< T >::ArePerpendicular().
IsPerpendicularTo() [2/2]
template<typename T> constexpr bool GPM::Vector4< T >::IsPerpendicularTo (const Vector4< T > & p_other) const
Return true if the two vectors are perpendicular.
Parameters
p_other The vector used for the checkup
Returns
True or false
Lerp() [1/2]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Lerp (const Vector4< T > & p_start, const Vector4< T > & p_end, const float p_interpolationCoefficient) static
Return the start vector moving to the end vector at step interpolationCoefficient.
Parameters
p_start The beginning vector
p_end The ending vector
p_interpolationCoefficient Between 0 and 1, 0 is start, 1 is end
Returns
The result vector
Definition at line 732 of file Vector4.inl.
     {
         if (p_interpolationCoefficient >= 0.0f && p_interpolationCoefficient <= 1.0f)
             return { p_start + (p_end - p_start) * p_interpolationCoefficient };
         if (p_interpolationCoefficient < 0.0f)
             return { p_start };
         return { p_end };
     }
Lerp() [2/2]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Lerp (const Vector4< T > & p_start, const Vector4< T > & p_end, const float p_interpolationCoefficient) static
Return the start vector moving to the end vector at step interpolationCoefficient.
Parameters
p_start The beginning vector
p_end The ending vector
p_interpolationCoefficient Between 0 and 1, 0 is start, 1 is end
Returns
The result vector
Magnitude() [1/4]
template<typename T > constexpr T GPM::Vector4< T >::Magnitude () const
Calculate the length of the vector.
Returns
The length of the vector
Definition at line 595 of file Vector4.inl.
     {
         return { static_cast<T>(Tools::Utils::SquareRootF(x * x + y * y + z * z)) };
     }
References GPM::Tools::Utils::SquareRootF().
Referenced by GPM::Vector4< T >::Angle(), and GPM::Vector4< T >::Magnitude().
Magnitude() [2/4]
template<typename T> constexpr T GPM::Vector4< T >::Magnitude () const
Calculate the length of the vector.
Returns
The length of the vector
Magnitude() [3/4]
template<typename T > constexpr T GPM::Vector4< T >::Magnitude (const Vector4< T > & p_vector) static
Calculate the length of the vector.
Parameters
p_vector The vector on which we calculate the magnitude
Returns
The length of the vector
Definition at line 601 of file Vector4.inl.
     {
         return { p_vector.Magnitude() };
     }
References GPM::Vector4< T >::Magnitude().
Magnitude() [4/4]
template<typename T> static constexpr T GPM::Vector4< T >::Magnitude (const Vector4< T > & p_vector) static
Calculate the length of the vector.
Parameters
p_vector The vector on which we calculate the magnitude
Returns
The length of the vector
MagnitudeSquare() [1/4]
template<typename T > constexpr T GPM::Vector4< T >::MagnitudeSquare () const
Calculate the squared length of the vector.
Returns
The length square of the vector
Definition at line 607 of file Vector4.inl.
     {
         return { static_cast<T>(x * x + y * y + z * z) };
     }
Referenced by GPM::Vector4< T >::MagnitudeSquare().
MagnitudeSquare() [2/4]
template<typename T> constexpr T GPM::Vector4< T >::MagnitudeSquare () const
Calculate the squared length of the vector.
Returns
The length square of the vector
MagnitudeSquare() [3/4]
template<typename T > constexpr T GPM::Vector4< T >::MagnitudeSquare (const Vector4< T > & p_vector) static
Calculate the squared length of the vector.
Parameters
p_vector The vector on which we calculate the square magnitude
Returns
The length square of the vector
Definition at line 613 of file Vector4.inl.
     {
         return { p_vector.MagnitudeSquare() };
     }
References GPM::Vector4< T >::MagnitudeSquare().
MagnitudeSquare() [4/4]
template<typename T> static constexpr T GPM::Vector4< T >::MagnitudeSquare (const Vector4< T > & p_vector) static
Calculate the squared length of the vector.
Parameters
p_vector The vector on which we calculate the square magnitude
Returns
The length square of the vector
Multiply() [1/12]
template<typename T > Vector4< T > & GPM::Vector4< T >::Multiply (const T p_scalar)
Multiply scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 353 of file Vector4.inl.
     {
         x *= p_scalar;
         y *= p_scalar;
         z *= p_scalar;
         return { *this };
     }
Referenced by GPM::Vector4< T >::Multiply(), and GPM::Vector4< T >::operator *().
Multiply() [2/12]
template<typename T> Vector4<T>& GPM::Vector4< T >::Multiply (const T p_scalar)
Multiply scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Multiply() [3/12]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Multiply (const U p_scalar)
Multiply scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Multiply() [4/12]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Multiply (const U p_scalar)
Multiply scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 364 of file Vector4.inl.
     {
         x *= p_scalar;
         y *= p_scalar;
         z *= p_scalar;
         return { *this };
     }
Multiply() [5/12]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Multiply (const Vector4< T > & p_left, T p_scalar) static
Multiply scalar to vector left.
Parameters
p_left The vector to multiply
p_scalar The scalar
Returns
The result vector
Multiply() [6/12]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Multiply (const Vector4< T > & p_left, T p_scalar) static
Multiply scalar to vector left.
Parameters
p_left The vector to multiply
p_scalar The scalar
Returns
The result vector
Definition at line 395 of file Vector4.inl.
     {
         return  { Vector4<T>(p_left).Multiply(p_scalar) };
     }
References GPM::Vector4< T >::Multiply().
Multiply() [7/12]
template<typename T> template<typename U > static constexpr Vector4<T> GPM::Vector4< T >::Multiply (const Vector4< T > & p_left, U p_scalar) static
Multiply scalar to vector left.
Parameters
p_left The vector to multiply
p_scalar The scalar
Returns
The result vector
Multiply() [8/12]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::Multiply (const Vector4< T > & p_left, U p_scalar) static
Multiply scalar to vector left.
Parameters
p_left The vector to multiply
p_scalar The scalar
Returns
The result vector
Definition at line 402 of file Vector4.inl.
     {
         return  { Vector4<T>(p_left).Multiply(p_scalar) };
     }
References GPM::Vector4< T >::Multiply().
Multiply() [9/12]
template<typename T> Vector4<T>& GPM::Vector4< T >::Multiply (const Vector4< T > & p_other)
Multiply other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Multiply() [10/12]
template<typename T > Vector4< T > & GPM::Vector4< T >::Multiply (const Vector4< T > & p_other)
Multiply other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 374 of file Vector4.inl.
     {
         x *= p_other.x;
         y *= p_other.y;
         z *= p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Multiply() [11/12]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Multiply (const Vector4< U > & p_other)
Multiply other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Multiply() [12/12]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Multiply (const Vector4< U > & p_other)
Multiply other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 385 of file Vector4.inl.
     {
         x *= p_other.x;
         y *= p_other.y;
         z *= p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Nlerp() [1/2]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Nlerp (const Vector4< T > & p_start, const Vector4< T > & p_end, const float p_interpolationCoefficient) static
Return the start vector moving to the end vector at step interpolationCoefficient.
Parameters
p_start The beginning vector
p_end The ending vector
p_interpolationCoefficient Between 0 and 1, 0 is start, 1 is end
Returns
The result vector
Nlerp() [2/2]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Nlerp (const Vector4< T > & p_start, const Vector4< T > & p_end, const float p_interpolationCoefficient) static
Return the start vector moving to the end vector at step interpolationCoefficient.
Parameters
p_start The beginning vector
p_end The ending vector
p_interpolationCoefficient Between 0 and 1, 0 is start, 1 is end
Returns
The result vector
Definition at line 764 of file Vector4.inl.
     {
         return Lerp(p_start, p_end, p_interpolationCoefficient).Normalize();
     }
Normalize() [1/4]
template<typename T > Vector4< T > & GPM::Vector4< T >::Normalize ()
Normalize the vector.
Returns
The current vector modified
Definition at line 688 of file Vector4.inl.
     {
         const float length = Magnitude();
         if (length > 0.0f)
         {
             x /= length;
             y /= length;
             z /= length;
         }
         return { *this };
     }
Referenced by GPM::Vector4< T >::IsParallelTo(), GPM::Vector4< T >::Normalize(), and GPM::Vector4< T >::Slerp().
Normalize() [2/4]
template<typename T> Vector4<T>& GPM::Vector4< T >::Normalize ()
Normalize the vector.
Returns
The current vector modified
Normalize() [3/4]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Normalize (const Vector4< T > & p_vector) static
Return the normalized vector.
Parameters
p_vector The vector to normalized
Returns
The result vector
Normalize() [4/4]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Normalize (const Vector4< T > & p_vector) static
Return the normalized vector.
Parameters
p_vector The vector to normalized
Returns
The result vector
Definition at line 703 of file Vector4.inl.
     {
         return { Vector4<T>(p_vector).Normalize() };
     }
References GPM::Vector4< T >::Normalize().
operator *() [1/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator * (const T p_scalar) const
Return the multiplication of scalar and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
operator *() [2/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator * (const T p_scalar) const
Return the multiplication of scalar and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
Definition at line 408 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Multiply(p_scalar) };
     }
References GPM::Vector4< T >::Multiply().
operator *() [3/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator * (const Vector4< T > & p_other) const
Return the multiplication of a vector and actual vector.
Parameters
p_other The scalar
Returns
The result vector
operator *() [4/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator * (const Vector4< T > & p_other) const
Return the multiplication of a vector and actual vector.
Parameters
p_other The scalar
Returns
The result vector
Definition at line 420 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Multiply(p_other) };
     }
References GPM::Vector4< T >::Multiply().
operator *() [5/6]
template<typename T> template<typename U > constexpr Vector4<T> GPM::Vector4< T >::operator * (const Vector4< U > & p_other) const
Return the multiplication of a vector and actual vector.
Parameters
p_other The vector
Returns
The result vector
operator *() [6/6]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::operator * (const Vector4< U > & p_other) const
Return the multiplication of a vector and actual vector.
Parameters
p_other The vector
Returns
The result vector
Definition at line 427 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Multiply(p_other) };
     }
References GPM::Vector4< T >::Multiply().
operator *=() [1/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator *= (const T p_scalar)
Multiply scalar to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
operator *=() [2/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator *= (const T p_scalar)
Multiply scalar to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 414 of file Vector4.inl.
     {
         return { Multiply(p_scalar) };
     }
operator *=() [3/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator *= (const Vector4< T > & p_other)
Multiply vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
operator *=() [4/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator *= (const Vector4< T > & p_other)
Multiply vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
Definition at line 433 of file Vector4.inl.
     {
         return { Multiply(p_other) };
     }
operator *=() [5/6]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::operator *= (const Vector4< U > & p_other)
Multiply vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
Definition at line 440 of file Vector4.inl.
     {
         return { Multiply(p_other) };
     }
operator *=() [6/6]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::operator *= (const Vector4< U > & p_other)
Multiply vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
operator+() [1/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator+ (const T p_scalar) const
Return the summation of other vector and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
Definition at line 203 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Add(p_scalar) };
     }
References GPM::Vector4< T >::Add().
operator+() [2/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator+ (const T p_scalar) const
Return the summation of other vector and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
operator+() [3/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator+ (const Vector4< T > & p_other) const
Return the summation of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
Definition at line 215 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Add(p_other) };
     }
References GPM::Vector4< T >::Add().
operator+() [4/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator+ (const Vector4< T > & p_other) const
Return the summation of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
operator+() [5/6]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::operator+ (const Vector4< U > & p_other) const
Return the summation of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
Definition at line 222 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Add(p_other) };
     }
References GPM::Vector4< T >::Add().
operator+() [6/6]
template<typename T> template<typename U > constexpr Vector4<T> GPM::Vector4< T >::operator+ (const Vector4< U > & p_other) const
Return the summation of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
operator+=() [1/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator+= (const T p_scalar)
Add other vector to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 209 of file Vector4.inl.
     {
         return { Add(p_scalar) };
     }
operator+=() [2/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator+= (const T p_scalar)
Add other vector to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
operator+=() [3/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator+= (const Vector4< T > & p_other)
Add other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 228 of file Vector4.inl.
     {
         return { Add(p_other) };
     }
operator+=() [4/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator+= (const Vector4< T > & p_other)
Add other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
operator+=() [5/6]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::operator+= (const Vector4< U > & p_other)
Add other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 235 of file Vector4.inl.
     {
         return { Add(p_other) };
     }
operator+=() [6/6]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::operator+= (const Vector4< U > & p_other)
Add other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
operator-() [1/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator- (const T p_scalar) const
Return the subtraction of other vector and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
Definition at line 312 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Subtract(p_scalar) };
     }
References GPM::Vector4< T >::Subtract().
operator-() [2/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator- (const T p_scalar) const
Return the subtraction of other vector and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
operator-() [3/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator- (const Vector4< T > & p_other) const
Return the subtraction of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
Definition at line 324 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Subtract(p_other) };
     }
References GPM::Vector4< T >::Subtract().
operator-() [4/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator- (const Vector4< T > & p_other) const
Return the subtraction of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
operator-() [5/6]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::operator- (const Vector4< U > & p_other) const
Return the subtraction of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
Definition at line 331 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Subtract(p_other) };
     }
References GPM::Vector4< T >::Subtract().
operator-() [6/6]
template<typename T> template<typename U > constexpr Vector4<T> GPM::Vector4< T >::operator- (const Vector4< U > & p_other) const
Return the subtraction of other vector and actual vector.
Parameters
p_other The other vector
Returns
The result vector
operator-=() [1/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator-= (const T p_scalar)
Subtract other vector to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 318 of file Vector4.inl.
     {
         return { Subtract(p_scalar) };
     }
operator-=() [2/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator-= (const T p_scalar)
Subtract other vector to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
operator-=() [3/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator-= (const Vector4< T > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The vector to use
Returns
The current vector modified
operator-=() [4/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator-= (const Vector4< T > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The vector to use
Returns
The current vector modified
Definition at line 337 of file Vector4.inl.
     {
         return { Subtract(p_other) };
     }
operator-=() [5/6]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::operator-= (const Vector4< U > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The vector to use
Returns
The current vector modified
Definition at line 344 of file Vector4.inl.
     {
         return { Subtract(p_other) };
     }
operator-=() [6/6]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::operator-= (const Vector4< U > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The vector to use
Returns
The current vector modified
operator/() [1/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator/ (const T p_scalar) const
Return the division of scalar and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
operator/() [2/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator/ (const T p_scalar) const
Return the division of scalar and actual vector.
Parameters
p_scalar The scalar
Returns
The result vector
Definition at line 516 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Divide(p_scalar) };
     }
References GPM::Vector4< T >::Divide().
operator/() [3/6]
template<typename T> constexpr Vector4<T> GPM::Vector4< T >::operator/ (const Vector4< T > & p_other) const
Return the division of a vector and actual vector.
Parameters
p_other The scalar
Returns
The result vector
operator/() [4/6]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::operator/ (const Vector4< T > & p_other) const
Return the division of a vector and actual vector.
Parameters
p_other The scalar
Returns
The result vector
Definition at line 528 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Divide(p_other) };
     }
References GPM::Vector4< T >::Divide().
operator/() [5/6]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::operator/ (const Vector4< U > & p_other) const
Return the division of a vector and actual vector.
Parameters
p_other The vector
Returns
The result vector
Definition at line 535 of file Vector4.inl.
     {
         return { Vector4<T>(*this).Divide(p_other) };
     }
References GPM::Vector4< T >::Divide().
operator/() [6/6]
template<typename T> template<typename U > constexpr Vector4<T> GPM::Vector4< T >::operator/ (const Vector4< U > & p_other) const
Return the division of a vector and actual vector.
Parameters
p_other The vector
Returns
The result vector
operator/=() [1/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator/= (const T p_scalar)
Divide scalar to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
operator/=() [2/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator/= (const T p_scalar)
Divide scalar to the actual vector.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 522 of file Vector4.inl.
     {
         return { Divide(p_scalar) };
     }
operator/=() [3/6]
template<typename T> Vector4<T>& GPM::Vector4< T >::operator/= (const Vector4< T > & p_other)
Divide vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
operator/=() [4/6]
template<typename T > Vector4< T > & GPM::Vector4< T >::operator/= (const Vector4< T > & p_other)
Divide vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
Definition at line 541 of file Vector4.inl.
     {
         return { Divide(p_other) };
     }
operator/=() [5/6]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::operator/= (const Vector4< U > & p_other)
Divide vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
Definition at line 548 of file Vector4.inl.
     {
         return { Divide(p_other) };
     }
operator/=() [6/6]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::operator/= (const Vector4< U > & p_other)
Divide vector to the actual vector.
Parameters
p_other The vector
Returns
The current vector modified
operator=() [1/4]
template<typename T > constexpr Vector4< T > & GPM::Vector4< T >::operator= (const Vector4< T > & p_other)
Overload = operator by copy.
Parameters
p_other The vector to construct from
Returns
The current vector modified
Definition at line 50 of file Vector4.inl.
     {
         x = p_other.x;
         y = p_other.y;
         z = p_other.z;
         w = p_other.w;
         return *this;
     }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
operator=() [2/4]
template<typename T> constexpr Vector4<T>& GPM::Vector4< T >::operator= (const Vector4< T > & p_other)
Overload = operator by copy.
Parameters
p_other The vector to construct from
Returns
The current vector modified
operator=() [3/4]
template<typename T> constexpr Vector4<T>& GPM::Vector4< T >::operator= (Vector4< T > && p_other) noexcept
Overload = operator by move.
Parameters
p_other The vector to construct from
Returns
The current vector modified
operator=() [4/4]
template<typename T > constexpr Vector4< T > & GPM::Vector4< T >::operator= (Vector4< T > && p_other) noexcept
Overload = operator by move.
Parameters
p_other The vector to construct from
Returns
The current vector modified
Definition at line 61 of file Vector4.inl.
     {
         x = p_other.x;
         y = p_other.y;
         z = p_other.z;
         w = p_other.w;
         return *this;
     }
operator==() [1/2]
template<typename T > constexpr bool GPM::Vector4< T >::operator== (const Vector4< T > & p_other) const
Return true if the two vectors are identical.
Parameters
p_other The vector used for the checkup
Returns
True or false
Definition at line 124 of file Vector4.inl.
     {
         return  { IsEqualTo(p_other) };
     }
operator==() [2/2]
template<typename T> constexpr bool GPM::Vector4< T >::operator== (const Vector4< T > & p_other) const
Return true if the two vectors are identical.
Parameters
p_other The vector used for the checkup
Returns
True or false
Scale() [1/4]
template<typename T> constexpr Vector4<T>& GPM::Vector4< T >::Scale (const T p_scale) const
Scale the vector with scalar.
Parameters
p_scale The scalar
Returns
The current vector modified
Scale() [2/4]
template<typename T > constexpr Vector4< T > & GPM::Vector4< T >::Scale (const T p_scale) const
Scale the vector with scalar.
Parameters
p_scale The scalar
Returns
The current vector modified
Definition at line 577 of file Vector4.inl.
     {
         x *= p_scale;
         y *= p_scale;
         z *= p_scale;
         return { *this };
     }
Scale() [3/4]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Scale (const Vector4< T > & p_vector, const T p_scale) static
Calculate the distance between the vector and another.
Parameters
p_vector The vector to scale
p_scale The scalar
Returns
The result vector
Scale() [4/4]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Scale (const Vector4< T > & p_vector, const T p_scale) static
Calculate the distance between the vector and another.
Parameters
p_vector The vector to scale
p_scale The scalar
Returns
The result vector
Definition at line 587 of file Vector4.inl.
     {
         const Vector4<T> result{ p_vector.x * p_scale , p_vector.y *= p_scale, p_vector.z *= p_scale, p_vector.w };
         return { result };
     }
References GPM::Vector4< T >::w, GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Slerp() [1/2]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Slerp (const Vector4< T > & p_start, const Vector4< T > & p_end, const float p_interpolationCoefficient) static
Return the start vector moving to the end vector at step interpolationCoefficient.
Parameters
p_start The beginning vector
p_end The ending vector
p_interpolationCoefficient Between 0 and 1, 0 is start, 1 is end
Returns
The result vector
Definition at line 745 of file Vector4.inl.
     {
         if (p_interpolationCoefficient >= 0.0f && p_interpolationCoefficient <= 1.0f)
         {
             const float angle = p_start.Angle(p_end) * p_interpolationCoefficient;
             Vector4<T> relativeVector = p_end - p_start * p_start.Dot(p_end);
             relativeVector.Normalize();
             return { (p_start * Tools::Utils::Cos(Tools::Utils::ToRadians(angle))) + (relativeVector * Tools::Utils::Sin(Tools::Utils::ToRadians(angle))) };
         }
         if (p_interpolationCoefficient < 0.0f)
             return { p_start };
         return { p_end };
     }
References GPM::Vector4< T >::Angle(), GPM::Tools::Utils::Cos(), GPM::Vector4< T >::Dot(), GPM::Vector4< T >::Normalize(), GPM::Tools::Utils::Sin(), and GPM::Tools::Utils::ToRadians().
Slerp() [2/2]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Slerp (const Vector4< T > & p_start, const Vector4< T > & p_end, const float p_interpolationCoefficient) static
Return the start vector moving to the end vector at step interpolationCoefficient.
Parameters
p_start The beginning vector
p_end The ending vector
p_interpolationCoefficient Between 0 and 1, 0 is start, 1 is end
Returns
The result vector
Subtract() [1/16]
template<typename T > Vector4< T > & GPM::Vector4< T >::Subtract (const T p_scalar)
Subtract scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 244 of file Vector4.inl.
     {
         x -= p_scalar;
         y -= p_scalar;
         z -= p_scalar;
         return { *this };
     }
Referenced by GPM::Vector4< T >::operator-(), and GPM::Vector4< T >::Subtract().
Subtract() [2/16]
template<typename T> Vector4<T>& GPM::Vector4< T >::Subtract (const T p_scalar)
Subtract scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Subtract() [3/16]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Subtract (const U p_scalar)
Subtract scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Subtract() [4/16]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Subtract (const U p_scalar)
Subtract scalar to x, y and z.
Parameters
p_scalar The scalar
Returns
The current vector modified
Definition at line 255 of file Vector4.inl.
     {
         x -= p_scalar;
         y -= p_scalar;
         z -= p_scalar;
         return { *this };
     }
Subtract() [5/16]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const T p_scalar) static
Subtract scalar to vector left.
Parameters
p_left The left vector
p_scalar The scalar
Returns
The result vector
Definition at line 265 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Subtract(p_scalar) };
     }
References GPM::Vector4< T >::Subtract().
Subtract() [6/16]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const T p_scalar) static
Subtract scalar to vector left.
Parameters
p_left The left vector
p_scalar The scalar
Returns
The result vector
Subtract() [7/16]
template<typename T> template<typename U > static constexpr Vector4<T> GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const U p_scalar) static
Subtract scalar to vector left.
Parameters
p_left The left vector
p_scalar The scalar
Returns
The result vector
Subtract() [8/16]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const U p_scalar) static
Subtract scalar to vector left.
Parameters
p_left The left vector
p_scalar The scalar
Returns
The result vector
Definition at line 272 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Subtract(p_scalar) };
     }
References GPM::Vector4< T >::Subtract().
Subtract() [9/16]
template<typename T > Vector4< T > & GPM::Vector4< T >::Subtract (const Vector4< T > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 278 of file Vector4.inl.
     {
         x -= p_other.x;
         y -= p_other.y;
         z -= p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Subtract() [10/16]
template<typename T> Vector4<T>& GPM::Vector4< T >::Subtract (const Vector4< T > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Subtract() [11/16]
template<typename T > template<typename U > Vector4< T > & GPM::Vector4< T >::Subtract (const Vector4< U > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Definition at line 289 of file Vector4.inl.
     {
         x -= p_other.x;
         y -= p_other.y;
         z -= p_other.z;
         return { *this };
     }
References GPM::Vector4< T >::x, GPM::Vector4< T >::y, and GPM::Vector4< T >::z.
Subtract() [12/16]
template<typename T> template<typename U > Vector4<T>& GPM::Vector4< T >::Subtract (const Vector4< U > & p_other)
Subtract other vector to the actual vector.
Parameters
p_other The other vector
Returns
The current vector modified
Subtract() [13/16]
template<typename T > constexpr Vector4< T > GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Subtract left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Definition at line 299 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Subtract(p_right) };
     }
References GPM::Vector4< T >::Subtract().
Subtract() [14/16]
template<typename T> static constexpr Vector4<T> GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const Vector4< T > & p_right) static
Subtract left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Subtract() [15/16]
template<typename T> template<typename U > static constexpr Vector4<T> GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const Vector4< U > & p_right) static
Subtract left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Subtract() [16/16]
template<typename T > template<typename U > constexpr Vector4< T > GPM::Vector4< T >::Subtract (const Vector4< T > & p_left, const Vector4< U > & p_right) static
Subtract left vector to the right vector.
Parameters
p_left The left vector
p_right The right vector
Returns
The result vector
Definition at line 306 of file Vector4.inl.
     {
         return { Vector4<T>(p_left).Subtract(p_right) };
     }
References GPM::Vector4< T >::Subtract().
ToString() [1/4]
template<typename T > constexpr std::string GPM::Vector4< T >::ToString () const
Convert vector to string.
Returns
The output string
Definition at line 774 of file Vector4.inl.
     {
         return { std::string("x : " + std::to_string(x) + " y : " + std::to_string(y) +
             " z : " + std::to_string(z) + " w : " + std::to_string(w)) };
     }
Referenced by GPM::Vector4< T >::ToString().
ToString() [2/4]
template<typename T> constexpr std::string GPM::Vector4< T >::ToString () const
Convert vector to string.
Returns
The output string
ToString() [3/4]
template<typename T > constexpr std::string GPM::Vector4< T >::ToString (const Vector4< T > & p_vector) static
Convert vector to string.
Parameters
p_vector The vector to print
Returns
The output string
Definition at line 781 of file Vector4.inl.
     {
         return { p_vector.ToString() };
     }
References GPM::Vector4< T >::ToString().
ToString() [4/4]
template<typename T> static constexpr std::string GPM::Vector4< T >::ToString (const Vector4< T > & p_vector) static
Convert vector to string.
Parameters
p_vector The vector to print
Returns
The output string
TripleProduct() [1/2]
template<typename T> static constexpr T GPM::Vector4< T >::TripleProduct (const Vector4< T > & p_left, const Vector4< T > & p_middle, const Vector4< T > & p_right) static
Calculate the dot product between left and the result of cross product between middle and right.
Parameters
p_left Left product
p_middle Middle vector
p_right Right vector
Returns
The result of the triple product
TripleProduct() [2/2]
template<typename T > constexpr T GPM::Vector4< T >::TripleProduct (const Vector4< T > & p_left, const Vector4< T > & p_middle, const Vector4< T > & p_right) static
Calculate the dot product between left and the result of cross product between middle and right.
Parameters
p_left Left product
p_middle Middle vector
p_right Right vector
Returns
The result of the triple product
Definition at line 658 of file Vector4.inl.
     {
         return p_middle * (Vector4<T>::Dot(p_left, p_right)) - p_right * (Vector4<T>::Dot(p_left, p_middle));
     }
References GPM::Vector4< T >::Dot().
Field Documentation
one
template<typename T> const Vector4< T > GPM::Vector4< T >::one = Vector4<T>(1, 1, 1, 1) static
Definition at line 21 of file Vector4.h.
w
template<typename T> T GPM::Vector4< T >::w
Definition at line 18 of file Vector4.h.
Referenced by GPM::Vector4< T >::Angle(), GPM::Vector4< T >::Cross(), GPM::Vector4< T >::Distance(), GPM::Vector4< T >::IsEqualTo(), GPM::Vector4< T >::IsHomogenized(), GPM::Matrix4< T >::Multiply(), GPM::operator<<(), GPM::Vector4< T >::operator=(), GPM::Vector4< T >::Scale(), GPM::Matrix4< T >::SetColumn(), and GPM::Matrix4< T >::SetRow().
x
template<typename T> T GPM::Vector4< T >::x
Definition at line 13 of file Vector4.h.
Referenced by GPM::Vector4< T >::Add(), GPM::Vector4< T >::Cross(), GPM::Vector4< T >::Distance(), GPM::Vector4< T >::Divide(), GPM::Vector4< T >::Dot(), GPM::Vector4< T >::IsEqualTo(), GPM::Vector4< T >::Multiply(), GPM::Matrix4< T >::Multiply(), GPM::operator<<(), GPM::Vector4< T >::operator=(), GPM::Vector4< T >::Scale(), GPM::Matrix4< T >::SetColumn(), GPM::Matrix4< T >::SetRow(), and GPM::Vector4< T >::Subtract().
xAxis
template<typename T> const Vector4< T > GPM::Vector4< T >::xAxis = Vector4<T>(1, 0, 0, 1) static
Definition at line 22 of file Vector4.h.
y
template<typename T> T GPM::Vector4< T >::y
Definition at line 16 of file Vector4.h.
Referenced by GPM::Vector4< T >::Add(), GPM::Vector4< T >::Cross(), GPM::Vector4< T >::Distance(), GPM::Vector4< T >::Divide(), GPM::Vector4< T >::Dot(), GPM::Vector4< T >::IsEqualTo(), GPM::Vector4< T >::Multiply(), GPM::Matrix4< T >::Multiply(), GPM::operator<<(), GPM::Vector4< T >::operator=(), GPM::Vector4< T >::Scale(), GPM::Matrix4< T >::SetColumn(), GPM::Matrix4< T >::SetRow(), and GPM::Vector4< T >::Subtract().
yAxis
template<typename T> const Vector4< T > GPM::Vector4< T >::yAxis = Vector4<T>(0, 1, 0, 1) static
Definition at line 23 of file Vector4.h.
z
template<typename T> T GPM::Vector4< T >::z
Definition at line 17 of file Vector4.h.
Referenced by GPM::Vector4< T >::Add(), GPM::Vector4< T >::Cross(), GPM::Vector4< T >::Distance(), GPM::Vector4< T >::Divide(), GPM::Vector4< T >::Dot(), GPM::Vector4< T >::IsEqualTo(), GPM::Vector4< T >::Multiply(), GPM::Matrix4< T >::Multiply(), GPM::operator<<(), GPM::Vector4< T >::operator=(), GPM::Vector4< T >::Scale(), GPM::Matrix4< T >::SetColumn(), GPM::Matrix4< T >::SetRow(), and GPM::Vector4< T >::Subtract().
zAxis
template<typename T> const Vector4< T > GPM::Vector4< T >::zAxis = Vector4<T>(0, 0, 1, 1) static
Definition at line 24 of file Vector4.h.
zero
template<typename T> const Vector4< T > GPM::Vector4< T >::zero = Vector4<T>(0, 0, 0, 1) static
Definition at line 20 of file Vector4.h.
Referenced by GPM::Matrix4< T >::Multiply().
The documentation for this struct was generated from the following files:
GPM/include/GPM/Vector/Vector4.h
GPM/include/GPM/Vector/Vector4.inl